# b.acceptance-verifier-loop — KPI

- **KPI-1 (no false done)**: ни один блок не уходит в `done` если хоть один пункт `acceptance.md` не получил `pass`. Сейчас (2026-09-22): ✓ — `lifecycle_gate.mjs` отказывает в `→ done` без verdict=pass, покрыто `lifecycle_gate.selftest` (группы 1, 5, 8).
- **KPI-2 (deterministic evidence first)**: ≥ 70% пунктов acceptance в среднем по репо имеют `evidence_kind ∈ {exit_code, fs_glob, file_diff, log_grep}` — без LLM. LLM-judge только как fallback. Сейчас (2026-09-22, R-8.11): ✓ — 89 из 122 = 73.0%. Пять проверок сняты с LLM-судьи на настоящие тесты (b.docs A3/A5, b.db A4, b.operator-profile-learner A7, b.smoke-sandbox A2). Считается доля всех пунктов приёмки по репо; `selftest_run` — вариант `exit_code`. Оставшиеся 33 на судье: 26 в демо-блоках продукта без кода, 7 — в реальных блоках, где нужна живая модель или живой UI.
- **KPI-3 (gate latency)**: для блока с ≤ 8 пунктами acceptance verifier завершается за < 30 секунд (deterministic) или < 60 секунд (с LLM-judge). Сейчас (2026-09-22): ✓ — этот блок, 8 пунктов, 1.1 с на моке.
- **KPI-4 (retry-prompt usefulness)**: ≥ 50% retry-прогонов с `retry_prompt_hint` приводят к verdict=pass на следующей итерации (на горизонте 20 retry). Сейчас: n/a.
- **KPI-5 (no spurious rollbacks)**: nightly re-verify done блоков даёт `done → broken` rollback **только** когда есть реальная регрессия (новые коммиты после последнего pass либо изменение acceptance.md). Сейчас: ✗.
- **KPI-6 (cache hit rate)**: при отсутствии новых коммитов / новых traces / новых checks.log — verifier возвращает кэш за < 50 ms. Hit rate ≥ 80% на nightly. Сейчас (2026-09-22, R-8.11): ✓ — `scripts/verify_cache.mjs`. Замер на двух nightly подряд без изменений между ними: 24 попадания из 27 = 88.9%, попадание p50 25.9 мс, p95 32.5 мс. Все 3 промаха законные (у блоков изменился файл, который читают их проверки). Корректность — `tests/verify_cache.selftest.mjs`: каждая часть ключа по отдельности сбрасывает кэш.
- **KPI-7 (cost cap)**: LLM-judge на один блок ≤ $0.02; полный nightly re-verify всех done блоков ≤ $0.20. Сейчас: ✗.
