// AUTO-GENERATED by scripts/generate_atlas_bootstrap_js.mjs — do not edit by hand
// Sources: atlas/graph.json + atlas/projects/*/graph.json + blocks/<id>/*.md
window.SIMA_BOOTSTRAP = {
  "data": {
    "projects": [
      {
        "id": "atlas-live",
        "name": "Sima Atlas",
        "taskKind": "продукт",
        "taskTitle": "Живая схема Atlas",
        "taskNote": "Блоки, слои, статусы и зависимости автогенерируются из /atlas",
        "created": "2026-05-03",
        "owner": "Cursor / Claude / Codex",
        "canvas": {
          "task": {
            "id": "t1",
            "x": 540,
            "y": 40,
            "w": 420,
            "h": 100,
            "title": "Sima Atlas",
            "subtitle": "Живая схема Atlas"
          },
          "sources": [
            {
              "id": "b.ui-control",
              "type": "artifact",
              "x": 120,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · wip",
              "title": "UI Control Plane",
              "meta": "b.ui-control",
              "take": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
              "tags": [
                "#wip",
                "#front"
              ]
            },
            {
              "id": "b.core-sync",
              "type": "artifact",
              "x": 350,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "logic · wip",
              "title": "Sync Engine",
              "meta": "b.core-sync",
              "take": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
              "tags": [
                "#wip",
                "#logic"
              ]
            },
            {
              "id": "b.agent-orchestrator",
              "type": "artifact",
              "x": 580,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "ai · review",
              "title": "Agent Orchestrator",
              "meta": "b.agent-orchestrator",
              "take": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
              "tags": [
                "#review",
                "#ai"
              ]
            },
            {
              "id": "b.llm-gateway",
              "type": "artifact",
              "x": 810,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "ai · review",
              "title": "LLM Gateway",
              "meta": "b.llm-gateway",
              "take": "Единая точка входа для всех LLM-вызовов внутри Атласа.",
              "tags": [
                "#review",
                "#ai"
              ]
            },
            {
              "id": "b.operator-profile-learner",
              "type": "artifact",
              "x": 120,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "ai · idea",
              "title": "Operator Profile Learner",
              "meta": "b.operator-profile-learner",
              "take": "Адаптивный модуль, который наблюдает за тем, **как именно** работает конкретный пользователь Атласа, запоминает его рабочие паттерны / стек / запреты / уроки из неудач, и адаптируе",
              "tags": [
                "#idea",
                "#ai"
              ]
            },
            {
              "id": "b.db",
              "type": "artifact",
              "x": 350,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "data · idea",
              "title": "Atlas Database",
              "meta": "b.db",
              "take": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
              "tags": [
                "#idea",
                "#data"
              ]
            },
            {
              "id": "b.docs",
              "type": "artifact",
              "x": 580,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "content · wip",
              "title": "Docs Builder",
              "meta": "b.docs",
              "take": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
              "tags": [
                "#wip",
                "#content"
              ]
            },
            {
              "id": "b.user-docs-generator",
              "type": "artifact",
              "x": 810,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "content · idea",
              "title": "End-User Docs Generator",
              "meta": "b.user-docs-generator",
              "take": "Атлас сам пишет UI и backend каждого пользовательского блока — следовательно, **знает** где какая кнопка, какой endpoint, какой happy path.",
              "tags": [
                "#idea",
                "#content"
              ]
            },
            {
              "id": "b.acceptance-verifier-loop",
              "type": "artifact",
              "x": 120,
              "y": 520,
              "w": 220,
              "h": 130,
              "source": "testing · idea",
              "title": "Acceptance Verifier Loop",
              "meta": "b.acceptance-verifier-loop",
              "take": "«Закрывающий контур» для каждого агент-прогона.",
              "tags": [
                "#idea",
                "#testing"
              ]
            },
            {
              "id": "b.smoke-sandbox",
              "type": "artifact",
              "x": 350,
              "y": 520,
              "w": 220,
              "h": 130,
              "source": "testing · idea",
              "title": "Smoke Sandbox (test target)",
              "meta": "b.smoke-sandbox",
              "take": "Целевой блок для всех e2e/smoke-тестов Атласа.",
              "tags": [
                "#idea",
                "#testing"
              ]
            }
          ],
          "links": [
            {
              "id": "b.ui-control__b.core-sync",
              "from": "b.ui-control",
              "to": "b.core-sync",
              "label": "b.ui-control → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.ui-control__b.agent-orchestrator",
              "from": "b.ui-control",
              "to": "b.agent-orchestrator",
              "label": "b.ui-control → b.agent-orchestrator",
              "direction": "to-task"
            },
            {
              "id": "b.core-sync__b.db",
              "from": "b.core-sync",
              "to": "b.db",
              "label": "b.core-sync → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.agent-orchestrator__b.db",
              "from": "b.agent-orchestrator",
              "to": "b.db",
              "label": "b.agent-orchestrator → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.agent-orchestrator__b.core-sync",
              "from": "b.agent-orchestrator",
              "to": "b.core-sync",
              "label": "b.agent-orchestrator → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.agent-orchestrator__b.llm-gateway",
              "from": "b.agent-orchestrator",
              "to": "b.llm-gateway",
              "label": "b.agent-orchestrator → b.llm-gateway",
              "direction": "to-task"
            },
            {
              "id": "b.docs__b.db",
              "from": "b.docs",
              "to": "b.db",
              "label": "b.docs → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.docs__b.core-sync",
              "from": "b.docs",
              "to": "b.core-sync",
              "label": "b.docs → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.operator-profile-learner__b.db",
              "from": "b.operator-profile-learner",
              "to": "b.db",
              "label": "b.operator-profile-learner → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.operator-profile-learner__b.core-sync",
              "from": "b.operator-profile-learner",
              "to": "b.core-sync",
              "label": "b.operator-profile-learner → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.operator-profile-learner__b.agent-orchestrator",
              "from": "b.operator-profile-learner",
              "to": "b.agent-orchestrator",
              "label": "b.operator-profile-learner → b.agent-orchestrator",
              "direction": "to-task"
            },
            {
              "id": "b.operator-profile-learner__b.llm-gateway",
              "from": "b.operator-profile-learner",
              "to": "b.llm-gateway",
              "label": "b.operator-profile-learner → b.llm-gateway",
              "direction": "to-task"
            },
            {
              "id": "b.operator-profile-learner__b.docs",
              "from": "b.operator-profile-learner",
              "to": "b.docs",
              "label": "b.operator-profile-learner → b.docs",
              "direction": "to-task"
            },
            {
              "id": "b.acceptance-verifier-loop__b.db",
              "from": "b.acceptance-verifier-loop",
              "to": "b.db",
              "label": "b.acceptance-verifier-loop → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.acceptance-verifier-loop__b.core-sync",
              "from": "b.acceptance-verifier-loop",
              "to": "b.core-sync",
              "label": "b.acceptance-verifier-loop → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.acceptance-verifier-loop__b.agent-orchestrator",
              "from": "b.acceptance-verifier-loop",
              "to": "b.agent-orchestrator",
              "label": "b.acceptance-verifier-loop → b.agent-orchestrator",
              "direction": "to-task"
            },
            {
              "id": "b.acceptance-verifier-loop__b.llm-gateway",
              "from": "b.acceptance-verifier-loop",
              "to": "b.llm-gateway",
              "label": "b.acceptance-verifier-loop → b.llm-gateway",
              "direction": "to-task"
            },
            {
              "id": "b.user-docs-generator__b.db",
              "from": "b.user-docs-generator",
              "to": "b.db",
              "label": "b.user-docs-generator → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.user-docs-generator__b.docs",
              "from": "b.user-docs-generator",
              "to": "b.docs",
              "label": "b.user-docs-generator → b.docs",
              "direction": "to-task"
            },
            {
              "id": "b.user-docs-generator__b.agent-orchestrator",
              "from": "b.user-docs-generator",
              "to": "b.agent-orchestrator",
              "label": "b.user-docs-generator → b.agent-orchestrator",
              "direction": "to-task"
            },
            {
              "id": "b.user-docs-generator__b.llm-gateway",
              "from": "b.user-docs-generator",
              "to": "b.llm-gateway",
              "label": "b.user-docs-generator → b.llm-gateway",
              "direction": "to-task"
            }
          ]
        },
        "map": {
          "mission": {
            "id": "m.mission",
            "title": "Миссия",
            "value": "Цель: единая визуально-документная система, которая устраняет рассинхрон между кодом, агентами и документацией.",
            "filled": true
          },
          "idea": {
            "id": "m.idea",
            "title": "Идея",
            "value": "Живая схема Atlas",
            "filled": true
          },
          "goal": {
            "id": "m.goal",
            "title": "JTBD",
            "value": "Блоки, слои, статусы и зависимости автогенерируются из /atlas",
            "filled": true
          },
          "audience": {
            "id": "m.audience",
            "title": "Для кого",
            "value": "Cursor / Claude / Codex",
            "filled": true
          },
          "value": {
            "id": "m.value",
            "title": "Ценность",
            "value": "См. project.md и user-stories блока",
            "filled": true
          },
          "important": {
            "id": "m.important",
            "title": "Должно быть",
            "items": [
              {
                "label": "UI Control Plane (front · wip)",
                "filled": true
              },
              {
                "label": "Sync Engine (logic · wip)",
                "filled": true
              },
              {
                "label": "Agent Orchestrator (ai · review)",
                "filled": true
              },
              {
                "label": "LLM Gateway (ai · review)",
                "filled": true
              },
              {
                "label": "Atlas Database (data · idea)",
                "filled": true
              },
              {
                "label": "Docs Builder (content · wip)",
                "filled": true
              }
            ]
          },
          "userstory": {
            "id": "m.us",
            "title": "User Story (по слоям)",
            "nodes": [
              {
                "id": "b.ui-control",
                "title": "UI Control Plane",
                "kind": "блок · front",
                "filled": true,
                "body": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
                "hasSubschema": true,
                "sources": [
                  "Sima (Remix)/Сима - универсальный конструктор.html [alive]",
                  "Sima (Remix)/index.html [alive] (PR4.1: ASCII alias for python http.server compatibility)",
                  "index.html [alive] (PR4.1: repo-root redirect to Sima (Remix)/index.html)",
                  "Sima (Remix)/app_v2.jsx [alive]",
                  "Sima (Remix)/arch_canvas.jsx [alive]"
                ]
              },
              {
                "id": "b.core-sync",
                "title": "Sync Engine",
                "kind": "блок · logic",
                "filled": true,
                "body": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/atlas_sync.js [alive] (client-side syncCheck + transitions)",
                  "scripts/validate_block_contracts.mjs [alive]",
                  "scripts/validate_dependency_contracts.mjs [alive]",
                  "scripts/validate_acceptance_assertions.mjs [alive]",
                  "scripts/validate_no_template_placeholders.mjs [alive] (PR1)"
                ]
              },
              {
                "id": "b.agent-orchestrator",
                "title": "Agent Orchestrator",
                "kind": "блок · ai",
                "filled": true,
                "body": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
                "hasSubschema": false,
                "sources": [
                  "scripts/mcp_atlas_server.mjs [alive] (21+ tools over JSON-RPC stdio)",
                  "scripts/atlas_api_server.mjs [alive] (HTTP facade for orchestration)",
                  "scripts/generate_cursor_hooks.mjs [alive] (PR4: emits valid Cursor format with real action scripts)",
                  "scripts/validate_cursor_hooks.mjs [alive] (PR4: gate; fails if hooks.json has wrong shape or missing scripts)",
                  "scripts/observe_file_edit.mjs [alive] (PR4: afterFileEdit action — files.md → block reverse-map)"
                ]
              },
              {
                "id": "b.llm-gateway",
                "title": "LLM Gateway",
                "kind": "блок · ai",
                "filled": true,
                "body": "Единая точка входа для всех LLM-вызовов внутри Атласа.",
                "hasSubschema": false,
                "sources": [
                  "scripts/llm_gateway.mjs [alive] (PR3 — main implementation, PR4.2 inline-comment-safe .env parser)",
                  "scripts/llm_check.mjs [alive] (PR4.1 — diagnostic for env + provider ping)",
                  "tests/llm_gateway.selftest.mjs [alive] (4 cases: schema validation, extractBlockSchema, trace write, no-schema fallback)",
                  "tests/llm_extraction.eval.mjs [alive] (5-case golden eval, target precision >= 0.7)",
                  "tests/fixtures/extraction_golden.json [alive]"
                ]
              },
              {
                "id": "b.operator-profile-learner",
                "title": "Operator Profile Learner",
                "kind": "блок · ai",
                "filled": true,
                "body": "Адаптивный модуль, который наблюдает за тем, **как именно** работает конкретный пользователь Атласа, запоминает его рабочие паттерны / стек / запреты / уроки из неудач, и адаптируе",
                "hasSubschema": false,
                "sources": [
                  "scripts/aggregate_operator_profile.mjs [alive]",
                  "atlas/operator_profile/profile.json [alive]",
                  "atlas/operator_profile/patterns/work_style.json [alive]",
                  "atlas/operator_profile/patterns/agents.json [alive]",
                  "atlas/operator_profile/patterns/tech_stack.json [alive]"
                ]
              },
              {
                "id": "b.db",
                "title": "Atlas Database",
                "kind": "блок · data",
                "filled": true,
                "body": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
                "hasSubschema": false,
                "sources": [
                  "atlas/graph.json [alive] (v2 — main schema source of truth)",
                  "atlas/db_schema.json [alive]",
                  "atlas/project.md [alive]",
                  "atlas/rules.md [alive]",
                  "atlas/tech_stack.md [alive] (project-wide stack lock)"
                ]
              },
              {
                "id": "b.docs",
                "title": "Docs Builder",
                "kind": "блок · content",
                "filled": true,
                "body": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
                "hasSubschema": false,
                "sources": [
                  "scripts/generate_wiki.mjs [alive]",
                  "scripts/generate_tz_from_atlas.mjs [alive]",
                  "scripts/render_wiki_html.mjs [alive]",
                  "scripts/rebuild_atlas_roadmap.mjs [alive]",
                  "scripts/generate_atlas_bootstrap_js.mjs [alive] (PR2 — emits layered bootstrap)"
                ]
              },
              {
                "id": "b.user-docs-generator",
                "title": "End-User Docs Generator",
                "kind": "блок · content",
                "filled": true,
                "body": "Атлас сам пишет UI и backend каждого пользовательского блока — следовательно, **знает** где какая кнопка, какой endpoint, какой happy path.",
                "hasSubschema": false,
                "sources": [
                  "scripts/introspect_block_ui.mjs [pending] (PR-1)",
                  "tests/fixtures/jsx/.gitkeep [pending] (PR-1)",
                  "tests/introspect_block_ui.selftest.mjs [pending] (PR-1)",
                  "scripts/generate_user_docs.mjs [pending] (PR-2: оркестратор)",
                  "tests/user_docs.smoke.mjs [pending] (PR-2)"
                ]
              },
              {
                "id": "b.acceptance-verifier-loop",
                "title": "Acceptance Verifier Loop",
                "kind": "блок · testing",
                "filled": true,
                "body": "«Закрывающий контур» для каждого агент-прогона.",
                "hasSubschema": false,
                "sources": [
                  "scripts/parse_acceptance.mjs [alive]",
                  "tests/parse_acceptance.selftest.mjs [alive]",
                  "scripts/collect_evidence.mjs [pending] (PR-2: диспетчер по evidence_kind)",
                  "tests/evidence_collectors.selftest.mjs [pending] (PR-2)",
                  "scripts/judge_assertion.mjs [pending] (PR-3)"
                ]
              },
              {
                "id": "b.smoke-sandbox",
                "title": "Smoke Sandbox (test target)",
                "kind": "блок · testing",
                "filled": true,
                "body": "Целевой блок для всех e2e/smoke-тестов Атласа.",
                "hasSubschema": false,
                "sources": [
                  "scripts/mcp_smoke_e2e.mjs [alive] (writes only into b.smoke-sandbox)",
                  "tests/atlas_sync.selftest.mjs [alive]"
                ]
              }
            ],
            "edges": [
              [
                "b.ui-control",
                "b.core-sync"
              ],
              [
                "b.ui-control",
                "b.agent-orchestrator"
              ],
              [
                "b.core-sync",
                "b.db"
              ],
              [
                "b.agent-orchestrator",
                "b.db"
              ],
              [
                "b.agent-orchestrator",
                "b.core-sync"
              ],
              [
                "b.agent-orchestrator",
                "b.llm-gateway"
              ],
              [
                "b.docs",
                "b.db"
              ],
              [
                "b.docs",
                "b.core-sync"
              ],
              [
                "b.operator-profile-learner",
                "b.db"
              ],
              [
                "b.operator-profile-learner",
                "b.core-sync"
              ],
              [
                "b.operator-profile-learner",
                "b.agent-orchestrator"
              ],
              [
                "b.operator-profile-learner",
                "b.llm-gateway"
              ],
              [
                "b.operator-profile-learner",
                "b.docs"
              ],
              [
                "b.acceptance-verifier-loop",
                "b.db"
              ],
              [
                "b.acceptance-verifier-loop",
                "b.core-sync"
              ],
              [
                "b.acceptance-verifier-loop",
                "b.agent-orchestrator"
              ],
              [
                "b.acceptance-verifier-loop",
                "b.llm-gateway"
              ],
              [
                "b.user-docs-generator",
                "b.db"
              ],
              [
                "b.user-docs-generator",
                "b.docs"
              ],
              [
                "b.user-docs-generator",
                "b.agent-orchestrator"
              ],
              [
                "b.user-docs-generator",
                "b.llm-gateway"
              ]
            ],
            "links": [
              {
                "from": "b.ui-control",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.ui-control",
                "to": "b.agent-orchestrator",
                "label": "depends_on"
              },
              {
                "from": "b.core-sync",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.agent-orchestrator",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.agent-orchestrator",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.agent-orchestrator",
                "to": "b.llm-gateway",
                "label": "depends_on"
              },
              {
                "from": "b.docs",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.docs",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.operator-profile-learner",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.operator-profile-learner",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.operator-profile-learner",
                "to": "b.agent-orchestrator",
                "label": "depends_on"
              },
              {
                "from": "b.operator-profile-learner",
                "to": "b.llm-gateway",
                "label": "depends_on"
              },
              {
                "from": "b.operator-profile-learner",
                "to": "b.docs",
                "label": "depends_on"
              },
              {
                "from": "b.acceptance-verifier-loop",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.acceptance-verifier-loop",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.acceptance-verifier-loop",
                "to": "b.agent-orchestrator",
                "label": "depends_on"
              },
              {
                "from": "b.acceptance-verifier-loop",
                "to": "b.llm-gateway",
                "label": "depends_on"
              },
              {
                "from": "b.user-docs-generator",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.user-docs-generator",
                "to": "b.docs",
                "label": "depends_on"
              },
              {
                "from": "b.user-docs-generator",
                "to": "b.agent-orchestrator",
                "label": "depends_on"
              },
              {
                "from": "b.user-docs-generator",
                "to": "b.llm-gateway",
                "label": "depends_on"
              }
            ]
          }
        },
        "tz": {
          "sections": [
            {
              "id": "s1",
              "num": "1",
              "title": "Миссия и цели"
            },
            {
              "id": "s2",
              "num": "2",
              "title": "Архитектура (по слоям)"
            },
            {
              "id": "s3",
              "num": "3",
              "title": "Блоки и контракты"
            },
            {
              "id": "s4",
              "num": "4",
              "title": "Roadmap и зависимости"
            },
            {
              "id": "s5",
              "num": "5",
              "title": "Sync-check и валидаторы"
            }
          ]
        },
        "impl": {
          "blocks": [
            {
              "id": "b.ui-control",
              "title": "UI Control Plane",
              "status": "wip",
              "layer": "front"
            },
            {
              "id": "b.core-sync",
              "title": "Sync Engine",
              "status": "wip",
              "layer": "logic"
            },
            {
              "id": "b.agent-orchestrator",
              "title": "Agent Orchestrator",
              "status": "review",
              "layer": "ai"
            },
            {
              "id": "b.llm-gateway",
              "title": "LLM Gateway",
              "status": "review",
              "layer": "ai"
            },
            {
              "id": "b.operator-profile-learner",
              "title": "Operator Profile Learner",
              "status": "idea",
              "layer": "ai"
            },
            {
              "id": "b.db",
              "title": "Atlas Database",
              "status": "idea",
              "layer": "data"
            },
            {
              "id": "b.docs",
              "title": "Docs Builder",
              "status": "wip",
              "layer": "content"
            },
            {
              "id": "b.user-docs-generator",
              "title": "End-User Docs Generator",
              "status": "idea",
              "layer": "content"
            },
            {
              "id": "b.acceptance-verifier-loop",
              "title": "Acceptance Verifier Loop",
              "status": "idea",
              "layer": "testing"
            },
            {
              "id": "b.smoke-sandbox",
              "title": "Smoke Sandbox (test target)",
              "status": "idea",
              "layer": "testing"
            }
          ]
        }
      },
      {
        "id": "demo-todo",
        "name": "Demo TODO",
        "taskKind": "продукт",
        "taskTitle": "Минимальный пример пользовательского продукта в Атласе, чтобы показать: Сима умеет вести **любой** продукт, не только сама себя.",
        "taskNote": "Project under atlas/projects/demo-todo",
        "created": "2026-05-03",
        "owner": "demo",
        "canvas": {
          "task": {
            "id": "t1",
            "x": 540,
            "y": 40,
            "w": 420,
            "h": 100,
            "title": "Demo TODO",
            "subtitle": "Минимальный пример пользовательского продукта в Атласе, чтобы показать: Сима умеет вести **любой** продукт, не только сама себя."
          },
          "sources": [
            {
              "id": "b.user-stories",
              "type": "artifact",
              "x": 120,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "user · review",
              "title": "User Stories",
              "meta": "b.user-stories",
              "take": "Каноничный набор пользовательских историй продукта Demo TODO.",
              "tags": [
                "#review",
                "#user"
              ]
            },
            {
              "id": "b.todo-ui",
              "type": "artifact",
              "x": 350,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · wip",
              "title": "TODO UI",
              "meta": "b.todo-ui",
              "take": "React SPA для Demo TODO.",
              "tags": [
                "#wip",
                "#front"
              ]
            },
            {
              "id": "b.todo-api",
              "type": "artifact",
              "x": 580,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "logic · wip",
              "title": "TODO API",
              "meta": "b.todo-api",
              "take": "Fastify-сервис, который реализует CRUD контракт `/todos` и подкладывает в БД через drizzle-orm.",
              "tags": [
                "#wip",
                "#logic"
              ]
            },
            {
              "id": "b.smart-categorizer",
              "type": "artifact",
              "x": 810,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "ai · idea",
              "title": "Smart Categorizer (LLM)",
              "meta": "b.smart-categorizer",
              "take": "Опциональный AI-помощник: при наборе нового todo (через POST /todos/categorize) подсказывает одну из существующих категорий.",
              "tags": [
                "#idea",
                "#ai"
              ]
            },
            {
              "id": "b.todo-db",
              "type": "artifact",
              "x": 120,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "data · idea",
              "title": "TODO Database",
              "meta": "b.todo-db",
              "take": "PostgreSQL 16 + drizzle-orm.",
              "tags": [
                "#idea",
                "#data"
              ]
            }
          ],
          "links": [
            {
              "id": "b.todo-ui__b.todo-api",
              "from": "b.todo-ui",
              "to": "b.todo-api",
              "label": "b.todo-ui → b.todo-api",
              "direction": "to-task"
            },
            {
              "id": "b.todo-ui__b.user-stories",
              "from": "b.todo-ui",
              "to": "b.user-stories",
              "label": "b.todo-ui → b.user-stories",
              "direction": "to-task"
            },
            {
              "id": "b.todo-api__b.todo-db",
              "from": "b.todo-api",
              "to": "b.todo-db",
              "label": "b.todo-api → b.todo-db",
              "direction": "to-task"
            },
            {
              "id": "b.smart-categorizer__b.todo-api",
              "from": "b.smart-categorizer",
              "to": "b.todo-api",
              "label": "b.smart-categorizer → b.todo-api",
              "direction": "to-task"
            }
          ]
        },
        "map": {
          "mission": {
            "id": "m.mission",
            "title": "Миссия",
            "value": "Минимальный пример пользовательского продукта в Атласе, чтобы показать: Сима умеет вести **любой** продукт, не только сама себя.",
            "filled": true
          },
          "idea": {
            "id": "m.idea",
            "title": "Идея",
            "value": "Минимальный пример пользовательского продукта в Атласе, чтобы показать: Сима умеет вести **любой** продукт, не только сама себя.",
            "filled": true
          },
          "goal": {
            "id": "m.goal",
            "title": "JTBD",
            "value": "Project under atlas/projects/demo-todo",
            "filled": true
          },
          "audience": {
            "id": "m.audience",
            "title": "Для кого",
            "value": "demo",
            "filled": true
          },
          "value": {
            "id": "m.value",
            "title": "Ценность",
            "value": "См. project.md и user-stories блока",
            "filled": true
          },
          "important": {
            "id": "m.important",
            "title": "Должно быть",
            "items": [
              {
                "label": "User Stories (user · review)",
                "filled": true
              },
              {
                "label": "TODO UI (front · wip)",
                "filled": true
              },
              {
                "label": "TODO API (logic · wip)",
                "filled": true
              },
              {
                "label": "TODO Database (data · idea)",
                "filled": true
              }
            ]
          },
          "userstory": {
            "id": "m.us",
            "title": "User Story (по слоям)",
            "nodes": [
              {
                "id": "b.user-stories",
                "title": "User Stories",
                "kind": "блок · user",
                "filled": true,
                "body": "Каноничный набор пользовательских историй продукта Demo TODO.",
                "hasSubschema": false,
                "sources": [
                  "atlas/projects/demo-todo/project.md [alive]",
                  "atlas/projects/demo-todo/blocks/b.user-stories/mission.md [alive]",
                  "atlas/projects/demo-todo/blocks/b.user-stories/acceptance.md [alive]"
                ]
              },
              {
                "id": "b.todo-ui",
                "title": "TODO UI",
                "kind": "блок · front",
                "filled": true,
                "body": "React SPA для Demo TODO.",
                "hasSubschema": false,
                "sources": [
                  "(none yet — files will be added in PR5+)"
                ]
              },
              {
                "id": "b.todo-api",
                "title": "TODO API",
                "kind": "блок · logic",
                "filled": true,
                "body": "Fastify-сервис, который реализует CRUD контракт `/todos` и подкладывает в БД через drizzle-orm.",
                "hasSubschema": false,
                "sources": [
                  "(none yet — files will be added in PR5+)"
                ]
              },
              {
                "id": "b.smart-categorizer",
                "title": "Smart Categorizer (LLM)",
                "kind": "блок · ai",
                "filled": true,
                "body": "Опциональный AI-помощник: при наборе нового todo (через POST /todos/categorize) подсказывает одну из существующих категорий.",
                "hasSubschema": false,
                "sources": [
                  "(none yet — files will be added in PR5+)"
                ]
              },
              {
                "id": "b.todo-db",
                "title": "TODO Database",
                "kind": "блок · data",
                "filled": true,
                "body": "PostgreSQL 16 + drizzle-orm.",
                "hasSubschema": false,
                "sources": [
                  "(none yet — files will be added in PR5+)"
                ]
              }
            ],
            "edges": [
              [
                "b.todo-ui",
                "b.todo-api"
              ],
              [
                "b.todo-ui",
                "b.user-stories"
              ],
              [
                "b.todo-api",
                "b.todo-db"
              ],
              [
                "b.smart-categorizer",
                "b.todo-api"
              ]
            ],
            "links": [
              {
                "from": "b.todo-ui",
                "to": "b.todo-api",
                "label": "depends_on"
              },
              {
                "from": "b.todo-ui",
                "to": "b.user-stories",
                "label": "depends_on"
              },
              {
                "from": "b.todo-api",
                "to": "b.todo-db",
                "label": "depends_on"
              },
              {
                "from": "b.smart-categorizer",
                "to": "b.todo-api",
                "label": "depends_on"
              }
            ]
          }
        },
        "tz": {
          "sections": [
            {
              "id": "s1",
              "num": "1",
              "title": "Миссия и цели"
            },
            {
              "id": "s2",
              "num": "2",
              "title": "Архитектура (по слоям)"
            },
            {
              "id": "s3",
              "num": "3",
              "title": "Блоки и контракты"
            },
            {
              "id": "s4",
              "num": "4",
              "title": "Roadmap и зависимости"
            },
            {
              "id": "s5",
              "num": "5",
              "title": "Sync-check и валидаторы"
            }
          ]
        },
        "impl": {
          "blocks": [
            {
              "id": "b.user-stories",
              "title": "User Stories",
              "status": "review",
              "layer": "user"
            },
            {
              "id": "b.todo-ui",
              "title": "TODO UI",
              "status": "wip",
              "layer": "front"
            },
            {
              "id": "b.todo-api",
              "title": "TODO API",
              "status": "wip",
              "layer": "logic"
            },
            {
              "id": "b.smart-categorizer",
              "title": "Smart Categorizer (LLM)",
              "status": "idea",
              "layer": "ai"
            },
            {
              "id": "b.todo-db",
              "title": "TODO Database",
              "status": "idea",
              "layer": "data"
            }
          ]
        }
      },
      {
        "id": "atlas-live:b.ui-control:components",
        "name": "UI Control Plane → components",
        "taskKind": "продукт",
        "taskTitle": "Подсхема блока b.ui-control",
        "taskNote": "Subschema \"components\" of atlas-live/b.ui-control",
        "created": "2026-05-03",
        "owner": "Cursor / Claude / Codex",
        "canvas": {
          "task": {
            "id": "t1",
            "x": 540,
            "y": 40,
            "w": 420,
            "h": 100,
            "title": "UI Control Plane → components",
            "subtitle": "Подсхема блока b.ui-control"
          },
          "sources": [
            {
              "id": "b.canvas",
              "type": "artifact",
              "x": 120,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · review",
              "title": "Arch Canvas",
              "meta": "b.canvas",
              "take": "SVG-канвас архитектурной схемы: рисует горизонтальные слои, блоки с портами, связи depends_on/data/path.",
              "tags": [
                "#review",
                "#front"
              ]
            },
            {
              "id": "b.inspector",
              "type": "artifact",
              "x": 350,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · review",
              "title": "Arch Inspector",
              "meta": "b.inspector",
              "take": "Правая панель инспектора блока: показывает mission/kpi/acceptance + lifecycle-кнопки (Implement/Review/Done/Rollback) + Run agent (PR4.",
              "tags": [
                "#review",
                "#front"
              ]
            },
            {
              "id": "b.tweaks-panel",
              "type": "artifact",
              "x": 580,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · done",
              "title": "Tweaks Panel",
              "meta": "b.tweaks-panel",
              "take": "Pop-up панель настроек UI: density / accent / canvas grid / artefacts view.",
              "tags": [
                "#done",
                "#front"
              ]
            },
            {
              "id": "b.composer",
              "type": "artifact",
              "x": 810,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · idea",
              "title": "Composer",
              "meta": "b.composer",
              "take": "Композитор задач для агентов: composer.",
              "tags": [
                "#idea",
                "#front"
              ]
            },
            {
              "id": "b.proposals-panel",
              "type": "artifact",
              "x": 120,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "front · review",
              "title": "Proposals Panel",
              "meta": "b.proposals-panel",
              "take": "Sidecol-панель PR3.5: рисует pending LLM-предложения по существующим блокам с цветным diff'ом и кнопками Accept/Reject.",
              "tags": [
                "#review",
                "#front"
              ]
            },
            {
              "id": "b.atlas-sync",
              "type": "artifact",
              "x": 350,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "logic · review",
              "title": "Atlas Sync (client)",
              "meta": "b.atlas-sync",
              "take": "Клиентская state machine: загружает atlas/<projId>/ из bootstrap, делает syncCheck (issues для drift/broken), persists в localStorage.",
              "tags": [
                "#review",
                "#logic"
              ]
            }
          ],
          "links": [
            {
              "id": "b.canvas__b.atlas-sync",
              "from": "b.canvas",
              "to": "b.atlas-sync",
              "label": "b.canvas → b.atlas-sync",
              "direction": "to-task"
            },
            {
              "id": "b.inspector__b.canvas",
              "from": "b.inspector",
              "to": "b.canvas",
              "label": "b.inspector → b.canvas",
              "direction": "to-task"
            },
            {
              "id": "b.inspector__b.atlas-sync",
              "from": "b.inspector",
              "to": "b.atlas-sync",
              "label": "b.inspector → b.atlas-sync",
              "direction": "to-task"
            },
            {
              "id": "b.proposals-panel__b.atlas-sync",
              "from": "b.proposals-panel",
              "to": "b.atlas-sync",
              "label": "b.proposals-panel → b.atlas-sync",
              "direction": "to-task"
            }
          ]
        },
        "map": {
          "mission": {
            "id": "m.mission",
            "title": "Миссия",
            "value": "Subschema \"components\" of atlas-live/b.ui-control",
            "filled": true
          },
          "idea": {
            "id": "m.idea",
            "title": "Идея",
            "value": "Подсхема блока b.ui-control",
            "filled": true
          },
          "goal": {
            "id": "m.goal",
            "title": "JTBD",
            "value": "Subschema \"components\" of atlas-live/b.ui-control",
            "filled": true
          },
          "audience": {
            "id": "m.audience",
            "title": "Для кого",
            "value": "Cursor / Claude / Codex",
            "filled": true
          },
          "value": {
            "id": "m.value",
            "title": "Ценность",
            "value": "См. project.md и user-stories блока",
            "filled": true
          },
          "important": {
            "id": "m.important",
            "title": "Должно быть",
            "items": [
              {
                "label": "Arch Canvas (front · review)",
                "filled": true
              },
              {
                "label": "Arch Inspector (front · review)",
                "filled": true
              },
              {
                "label": "Proposals Panel (front · review)",
                "filled": true
              },
              {
                "label": "Atlas Sync (client) (logic · review)",
                "filled": true
              }
            ]
          },
          "userstory": {
            "id": "m.us",
            "title": "User Story (по слоям)",
            "nodes": [
              {
                "id": "b.canvas",
                "title": "Arch Canvas",
                "kind": "блок · front",
                "filled": true,
                "body": "SVG-канвас архитектурной схемы: рисует горизонтальные слои, блоки с портами, связи depends_on/data/path.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/arch_canvas.jsx [alive]"
                ]
              },
              {
                "id": "b.inspector",
                "title": "Arch Inspector",
                "kind": "блок · front",
                "filled": true,
                "body": "Правая панель инспектора блока: показывает mission/kpi/acceptance + lifecycle-кнопки (Implement/Review/Done/Rollback) + Run agent (PR4.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/arch_canvas.jsx [alive]"
                ]
              },
              {
                "id": "b.tweaks-panel",
                "title": "Tweaks Panel",
                "kind": "блок · front",
                "filled": true,
                "body": "Pop-up панель настроек UI: density / accent / canvas grid / artefacts view.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/tweaks-panel.jsx [alive]"
                ]
              },
              {
                "id": "b.composer",
                "title": "Composer",
                "kind": "блок · front",
                "filled": true,
                "body": "Композитор задач для агентов: composer.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/composer.jsx [alive]"
                ]
              },
              {
                "id": "b.proposals-panel",
                "title": "Proposals Panel",
                "kind": "блок · front",
                "filled": true,
                "body": "Sidecol-панель PR3.5: рисует pending LLM-предложения по существующим блокам с цветным diff'ом и кнопками Accept/Reject.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/proposals_panel.jsx [alive]"
                ]
              },
              {
                "id": "b.atlas-sync",
                "title": "Atlas Sync (client)",
                "kind": "блок · logic",
                "filled": true,
                "body": "Клиентская state machine: загружает atlas/<projId>/ из bootstrap, делает syncCheck (issues для drift/broken), persists в localStorage.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/atlas_sync.js [alive]"
                ]
              }
            ],
            "edges": [
              [
                "b.canvas",
                "b.atlas-sync"
              ],
              [
                "b.inspector",
                "b.canvas"
              ],
              [
                "b.inspector",
                "b.atlas-sync"
              ],
              [
                "b.proposals-panel",
                "b.atlas-sync"
              ]
            ],
            "links": [
              {
                "from": "b.canvas",
                "to": "b.atlas-sync",
                "label": "depends_on"
              },
              {
                "from": "b.inspector",
                "to": "b.canvas",
                "label": "depends_on"
              },
              {
                "from": "b.inspector",
                "to": "b.atlas-sync",
                "label": "depends_on"
              },
              {
                "from": "b.proposals-panel",
                "to": "b.atlas-sync",
                "label": "depends_on"
              }
            ]
          }
        },
        "tz": {
          "sections": [
            {
              "id": "s1",
              "num": "1",
              "title": "Миссия и цели"
            },
            {
              "id": "s2",
              "num": "2",
              "title": "Архитектура (по слоям)"
            },
            {
              "id": "s3",
              "num": "3",
              "title": "Блоки и контракты"
            },
            {
              "id": "s4",
              "num": "4",
              "title": "Roadmap и зависимости"
            },
            {
              "id": "s5",
              "num": "5",
              "title": "Sync-check и валидаторы"
            }
          ]
        },
        "impl": {
          "blocks": [
            {
              "id": "b.canvas",
              "title": "Arch Canvas",
              "status": "review",
              "layer": "front"
            },
            {
              "id": "b.inspector",
              "title": "Arch Inspector",
              "status": "review",
              "layer": "front"
            },
            {
              "id": "b.tweaks-panel",
              "title": "Tweaks Panel",
              "status": "done",
              "layer": "front"
            },
            {
              "id": "b.composer",
              "title": "Composer",
              "status": "idea",
              "layer": "front"
            },
            {
              "id": "b.proposals-panel",
              "title": "Proposals Panel",
              "status": "review",
              "layer": "front"
            },
            {
              "id": "b.atlas-sync",
              "title": "Atlas Sync (client)",
              "status": "review",
              "layer": "logic"
            }
          ]
        },
        "parent": {
          "projectId": "atlas-live",
          "blockId": "b.ui-control",
          "subId": "components"
        }
      }
    ]
  },
  "archByProject": {
    "atlas-live": {
      "projectId": "atlas-live",
      "layers": [
        "front",
        "logic",
        "ai",
        "data",
        "content",
        "testing"
      ],
      "blocks": [
        {
          "id": "b.ui-control",
          "title": "UI Control Plane",
          "layer": "front",
          "type": "module",
          "status": "wip",
          "status_reason": "HTML loses references to components.jsx/sidecol.jsx/canvas_tools.jsx — UI does not boot in production; multi-layer rendering depends on PR2 (this PR)",
          "mvp": true,
          "subschema": "components",
          "x": 40,
          "w": 210,
          "note": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
          "sources": [
            "Sima (Remix)/Сима - универсальный конструктор.html [alive]",
            "Sima (Remix)/index.html [alive] (PR4.1: ASCII alias for python http.server compatibility)",
            "index.html [alive] (PR4.1: repo-root redirect to Sima (Remix)/index.html)",
            "Sima (Remix)/app_v2.jsx [alive]",
            "Sima (Remix)/arch_canvas.jsx [alive]"
          ],
          "tech_stack": [
            "react",
            "babel-standalone"
          ]
        },
        {
          "id": "b.core-sync",
          "title": "Sync Engine",
          "layer": "logic",
          "type": "module",
          "status": "wip",
          "status_reason": "syncCheck only validates file presence, not mission/KPI semantics",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
          "sources": [
            "Sima (Remix)/atlas_sync.js [alive] (client-side syncCheck + transitions)",
            "scripts/validate_block_contracts.mjs [alive]",
            "scripts/validate_dependency_contracts.mjs [alive]",
            "scripts/validate_acceptance_assertions.mjs [alive]",
            "scripts/validate_no_template_placeholders.mjs [alive] (PR1)"
          ],
          "tech_stack": [
            "nodejs",
            "esm"
          ]
        },
        {
          "id": "b.agent-orchestrator",
          "title": "Agent Orchestrator",
          "layer": "ai",
          "type": "module",
          "status": "review",
          "status_reason": "PR4: .cursor/hooks.json now uses valid Cursor events (beforeSubmitPrompt/afterFileEdit/beforeShellExecution/stop) wired to real action scripts. Cursor edits write to checks.log of the right block via files.md mapping. Drift guard rejects pip/yarn-add-vue/etc. inject_context_pack provides per-block context. Live Cursor wiring (real env vars) needs UI test (PR4.5).",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
          "sources": [
            "scripts/mcp_atlas_server.mjs [alive] (21+ tools over JSON-RPC stdio)",
            "scripts/atlas_api_server.mjs [alive] (HTTP facade for orchestration)",
            "scripts/generate_cursor_hooks.mjs [alive] (PR4: emits valid Cursor format with real action scripts)",
            "scripts/validate_cursor_hooks.mjs [alive] (PR4: gate; fails if hooks.json has wrong shape or missing scripts)",
            "scripts/observe_file_edit.mjs [alive] (PR4: afterFileEdit action — files.md → block reverse-map)"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "mcp"
          ]
        },
        {
          "id": "b.llm-gateway",
          "title": "LLM Gateway",
          "layer": "ai",
          "type": "module",
          "status": "review",
          "status_reason": "PR3: gateway implemented (Anthropic + Google + mock), structured output via JSON schema, trace+cost cap, golden eval avg 1.0 in mock. Review needed: live providers untested without keys; UI confidence/diff flow pending PR3.5.",
          "mvp": true,
          "subschema": null,
          "x": 270,
          "w": 210,
          "note": "Единая точка входа для всех LLM-вызовов внутри Атласа.",
          "sources": [
            "scripts/llm_gateway.mjs [alive] (PR3 — main implementation, PR4.2 inline-comment-safe .env parser)",
            "scripts/llm_check.mjs [alive] (PR4.1 — diagnostic for env + provider ping)",
            "tests/llm_gateway.selftest.mjs [alive] (4 cases: schema validation, extractBlockSchema, trace write, no-schema fallback)",
            "tests/llm_extraction.eval.mjs [alive] (5-case golden eval, target precision >= 0.7)",
            "tests/fixtures/extraction_golden.json [alive]"
          ],
          "tech_stack": [
            "nodejs",
            "anthropic-api",
            "google-genai-api"
          ]
        },
        {
          "id": "b.operator-profile-learner",
          "title": "Operator Profile Learner",
          "layer": "ai",
          "type": "module",
          "status": "idea",
          "status_reason": "PR-Backlog: design-only milestone; one of the LAST PRs. Реальная имплементация (PR-1…PR-6) делается после того, как реальный пользователь пройдёт ≥10 done и накопит данные — иначе наблюдать нечего. Сейчас зарегистрирован как карта будущей работы.",
          "mvp": false,
          "subschema": null,
          "x": 500,
          "w": 210,
          "note": "Адаптивный модуль, который наблюдает за тем, **как именно** работает конкретный пользователь Атласа, запоминает его рабочие паттерны / стек / запреты / уроки из неудач, и адаптируе",
          "sources": [
            "scripts/aggregate_operator_profile.mjs [alive]",
            "atlas/operator_profile/profile.json [alive]",
            "atlas/operator_profile/patterns/work_style.json [alive]",
            "atlas/operator_profile/patterns/agents.json [alive]",
            "atlas/operator_profile/patterns/tech_stack.json [alive]"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "json"
          ]
        },
        {
          "id": "b.db",
          "title": "Atlas Database",
          "layer": "data",
          "type": "module",
          "status": "idea",
          "status_reason": "Storage is markdown + localStorage; no real DB layer yet",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
          "sources": [
            "atlas/graph.json [alive] (v2 — main schema source of truth)",
            "atlas/db_schema.json [alive]",
            "atlas/project.md [alive]",
            "atlas/rules.md [alive]",
            "atlas/tech_stack.md [alive] (project-wide stack lock)"
          ],
          "tech_stack": [
            "filesystem",
            "json",
            "markdown"
          ]
        },
        {
          "id": "b.docs",
          "title": "Docs Builder",
          "layer": "content",
          "type": "module",
          "status": "wip",
          "status_reason": "Generators run but feed on template missions; needs layer-aware wiki and mermaid (PR2)",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
          "sources": [
            "scripts/generate_wiki.mjs [alive]",
            "scripts/generate_tz_from_atlas.mjs [alive]",
            "scripts/render_wiki_html.mjs [alive]",
            "scripts/rebuild_atlas_roadmap.mjs [alive]",
            "scripts/generate_atlas_bootstrap_js.mjs [alive] (PR2 — emits layered bootstrap)"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "markdown"
          ]
        },
        {
          "id": "b.user-docs-generator",
          "title": "End-User Docs Generator",
          "layer": "content",
          "type": "module",
          "status": "idea",
          "status_reason": "PR-Backlog: design-only milestone. Closes the end-user tutorial gap — Атлас сам пишет UI блоков, значит знает все кнопки и поля; этот блок генерирует 'как пользоваться' markdown для конечного пользователя продукта (не developer wiki — это делает b.docs). Auto-regen на каждое изменение JSX. 3-4 PR breakdown.",
          "mvp": false,
          "subschema": null,
          "x": 270,
          "w": 210,
          "note": "Атлас сам пишет UI и backend каждого пользовательского блока — следовательно, **знает** где какая кнопка, какой endpoint, какой happy path.",
          "sources": [
            "scripts/introspect_block_ui.mjs [pending] (PR-1)",
            "tests/fixtures/jsx/.gitkeep [pending] (PR-1)",
            "tests/introspect_block_ui.selftest.mjs [pending] (PR-1)",
            "scripts/generate_user_docs.mjs [pending] (PR-2: оркестратор)",
            "tests/user_docs.smoke.mjs [pending] (PR-2)"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "markdown",
            "playwright"
          ]
        },
        {
          "id": "b.acceptance-verifier-loop",
          "title": "Acceptance Verifier Loop",
          "layer": "testing",
          "type": "module",
          "status": "idea",
          "status_reason": "PR-Backlog: design-only milestone. Closes the verification gap (Symphony trusts agent output, Hermes has no contract layer). После любого run_block_implementation проверяет каждый пункт acceptance.md через детерминированные collectors (exit_code/fs_glob/file_diff/log_grep) + LLM-judge fallback; блокирует wip→done если verdict !== pass. 5-PR breakdown.",
          "mvp": false,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "«Закрывающий контур» для каждого агент-прогона.",
          "sources": [
            "scripts/parse_acceptance.mjs [alive]",
            "tests/parse_acceptance.selftest.mjs [alive]",
            "scripts/collect_evidence.mjs [pending] (PR-2: диспетчер по evidence_kind)",
            "tests/evidence_collectors.selftest.mjs [pending] (PR-2)",
            "scripts/judge_assertion.mjs [pending] (PR-3)"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "json-schema"
          ]
        },
        {
          "id": "b.smoke-sandbox",
          "title": "Smoke Sandbox (test target)",
          "layer": "testing",
          "type": "test",
          "status": "idea",
          "status_reason": "Reserved write-target for e2e/smoke scripts so they never touch real product blocks",
          "mvp": false,
          "subschema": null,
          "x": 270,
          "w": 210,
          "note": "Целевой блок для всех e2e/smoke-тестов Атласа.",
          "sources": [
            "scripts/mcp_smoke_e2e.mjs [alive] (writes only into b.smoke-sandbox)",
            "tests/atlas_sync.selftest.mjs [alive]"
          ],
          "tech_stack": []
        }
      ],
      "links": [
        {
          "from": "b.ui-control",
          "to": "b.core-sync",
          "type": "dep",
          "label": "sync_report",
          "capability": "sync_report",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.ui-control",
          "to": "b.agent-orchestrator",
          "type": "dep",
          "label": "pipeline_execution",
          "capability": "pipeline_execution",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.core-sync",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.agent-orchestrator",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.agent-orchestrator",
          "to": "b.core-sync",
          "type": "dep",
          "label": "sync_report",
          "capability": "sync_report",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.agent-orchestrator",
          "to": "b.llm-gateway",
          "type": "dep",
          "label": "",
          "capability": null,
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.docs",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.docs",
          "to": "b.core-sync",
          "type": "dep",
          "label": "sync_report",
          "capability": "sync_report",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.operator-profile-learner",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.operator-profile-learner",
          "to": "b.core-sync",
          "type": "dep",
          "label": "sync_report",
          "capability": "sync_report",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.operator-profile-learner",
          "to": "b.agent-orchestrator",
          "type": "dep",
          "label": "pipeline_execution",
          "capability": "pipeline_execution",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.operator-profile-learner",
          "to": "b.llm-gateway",
          "type": "dep",
          "label": "llm_call_structured",
          "capability": "llm_call_structured",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.operator-profile-learner",
          "to": "b.docs",
          "type": "dep",
          "label": "wiki_bundle",
          "capability": "wiki_bundle",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.acceptance-verifier-loop",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.acceptance-verifier-loop",
          "to": "b.core-sync",
          "type": "dep",
          "label": "sync_report",
          "capability": "sync_report",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.acceptance-verifier-loop",
          "to": "b.agent-orchestrator",
          "type": "dep",
          "label": "pipeline_execution",
          "capability": "pipeline_execution",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.acceptance-verifier-loop",
          "to": "b.llm-gateway",
          "type": "dep",
          "label": "llm_call_structured",
          "capability": "llm_call_structured",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.user-docs-generator",
          "to": "b.db",
          "type": "dep",
          "label": "atlas_state_store",
          "capability": "atlas_state_store",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.user-docs-generator",
          "to": "b.docs",
          "type": "dep",
          "label": "wiki_bundle",
          "capability": "wiki_bundle",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.user-docs-generator",
          "to": "b.agent-orchestrator",
          "type": "dep",
          "label": "pipeline_execution",
          "capability": "pipeline_execution",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.user-docs-generator",
          "to": "b.llm-gateway",
          "type": "dep",
          "label": "llm_call_structured",
          "capability": "llm_call_structured",
          "broken": false,
          "broken_reason": null
        }
      ],
      "groups": []
    },
    "demo-todo": {
      "projectId": "demo-todo",
      "layers": [
        "user",
        "front",
        "logic",
        "ai",
        "data"
      ],
      "blocks": [
        {
          "id": "b.user-stories",
          "title": "User Stories",
          "layer": "user",
          "type": "module",
          "status": "review",
          "status_reason": "User stories drafted; need acceptance test cases per story before done",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Каноничный набор пользовательских историй продукта Demo TODO.",
          "sources": [
            "atlas/projects/demo-todo/project.md [alive]",
            "atlas/projects/demo-todo/blocks/b.user-stories/mission.md [alive]",
            "atlas/projects/demo-todo/blocks/b.user-stories/acceptance.md [alive]"
          ],
          "tech_stack": []
        },
        {
          "id": "b.todo-ui",
          "title": "TODO UI",
          "layer": "front",
          "type": "module",
          "status": "wip",
          "status_reason": "Frontend SPA: Add/Toggle/Delete + filter by category; Tailwind layout TBD",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "React SPA для Demo TODO.",
          "sources": [
            "(none yet — files will be added in PR5+)"
          ],
          "tech_stack": [
            "react",
            "vite",
            "typescript",
            "tailwindcss"
          ]
        },
        {
          "id": "b.todo-api",
          "title": "TODO API",
          "layer": "logic",
          "type": "module",
          "status": "wip",
          "status_reason": "Fastify routes: GET/POST/PATCH/DELETE /todos; integration tests pending",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Fastify-сервис, который реализует CRUD контракт `/todos` и подкладывает в БД через drizzle-orm.",
          "sources": [
            "(none yet — files will be added in PR5+)"
          ],
          "tech_stack": [
            "nodejs",
            "fastify",
            "typescript",
            "drizzle-orm"
          ]
        },
        {
          "id": "b.smart-categorizer",
          "title": "Smart Categorizer (LLM)",
          "layer": "ai",
          "type": "module",
          "status": "idea",
          "status_reason": "Optional MVP+1 feature: classify a new task into an existing category via b.llm-gateway",
          "mvp": false,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Опциональный AI-помощник: при наборе нового todo (через POST /todos/categorize) подсказывает одну из существующих категорий.",
          "sources": [
            "(none yet — files will be added in PR5+)"
          ],
          "tech_stack": [
            "nodejs"
          ]
        },
        {
          "id": "b.todo-db",
          "title": "TODO Database",
          "layer": "data",
          "type": "module",
          "status": "idea",
          "status_reason": "Schema sketch only: todos(id, text, category, done, created_at). Migration not written.",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "PostgreSQL 16 + drizzle-orm.",
          "sources": [
            "(none yet — files will be added in PR5+)"
          ],
          "tech_stack": [
            "postgresql",
            "drizzle-orm"
          ]
        }
      ],
      "links": [
        {
          "from": "b.todo-ui",
          "to": "b.todo-api",
          "type": "dep",
          "label": "todo_crud_endpoints",
          "capability": "todo_crud_endpoints",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.todo-ui",
          "to": "b.user-stories",
          "type": "dep",
          "label": "user_story_catalog",
          "capability": "user_story_catalog",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.todo-api",
          "to": "b.todo-db",
          "type": "dep",
          "label": "todos_table",
          "capability": "todos_table",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.smart-categorizer",
          "to": "b.todo-api",
          "type": "dep",
          "label": "todo_crud_endpoints",
          "capability": "todo_crud_endpoints",
          "broken": false,
          "broken_reason": null
        }
      ],
      "groups": []
    },
    "atlas-live:b.ui-control:components": {
      "projectId": "atlas-live:b.ui-control:components",
      "layers": [
        "front",
        "logic"
      ],
      "blocks": [
        {
          "id": "b.canvas",
          "title": "Arch Canvas",
          "layer": "front",
          "type": "module",
          "status": "review",
          "status_reason": "PR2.5 added drift visualization; needs subschema double-click + zoom-to-fit (PR-Sub2)",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "SVG-канвас архитектурной схемы: рисует горизонтальные слои, блоки с портами, связи depends_on/data/path.",
          "sources": [
            "Sima (Remix)/arch_canvas.jsx [alive]"
          ],
          "tech_stack": [
            "react",
            "babel-standalone"
          ]
        },
        {
          "id": "b.inspector",
          "title": "Arch Inspector",
          "layer": "front",
          "type": "module",
          "status": "review",
          "status_reason": "PR2.5 surfaces drift issues; PR3.5 needs richer Accept/Reject layout for proposals",
          "mvp": true,
          "subschema": null,
          "x": 270,
          "w": 210,
          "note": "Правая панель инспектора блока: показывает mission/kpi/acceptance + lifecycle-кнопки (Implement/Review/Done/Rollback) + Run agent (PR4.",
          "sources": [
            "Sima (Remix)/arch_canvas.jsx [alive]"
          ],
          "tech_stack": [
            "react"
          ]
        },
        {
          "id": "b.tweaks-panel",
          "title": "Tweaks Panel",
          "layer": "front",
          "type": "module",
          "status": "done",
          "status_reason": "Density/accent toggles working; no live regressions",
          "mvp": false,
          "subschema": null,
          "x": 500,
          "w": 210,
          "note": "Pop-up панель настроек UI: density / accent / canvas grid / artefacts view.",
          "sources": [
            "Sima (Remix)/tweaks-panel.jsx [alive]"
          ],
          "tech_stack": [
            "react"
          ]
        },
        {
          "id": "b.composer",
          "title": "Composer",
          "layer": "front",
          "type": "module",
          "status": "idea",
          "status_reason": "Composer.jsx exists but not yet wired to /run-block — PR4.5 wires Run-agent button instead",
          "mvp": false,
          "subschema": null,
          "x": 730,
          "w": 210,
          "note": "Композитор задач для агентов: composer.",
          "sources": [
            "Sima (Remix)/composer.jsx [alive]"
          ],
          "tech_stack": [
            "react"
          ]
        },
        {
          "id": "b.proposals-panel",
          "title": "Proposals Panel",
          "layer": "front",
          "type": "module",
          "status": "review",
          "status_reason": "PR3.5 ready; needs live test against atlas_api_server to confirm Accept/Reject buttons fully round-trip",
          "mvp": true,
          "subschema": null,
          "x": 960,
          "w": 210,
          "note": "Sidecol-панель PR3.5: рисует pending LLM-предложения по существующим блокам с цветным diff'ом и кнопками Accept/Reject.",
          "sources": [
            "Sima (Remix)/proposals_panel.jsx [alive]"
          ],
          "tech_stack": [
            "react"
          ]
        },
        {
          "id": "b.atlas-sync",
          "title": "Atlas Sync (client)",
          "layer": "logic",
          "type": "module",
          "status": "review",
          "status_reason": "Client-side state machine + syncCheck; PR3.6 hardened against undefined-JSON crash",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Клиентская state machine: загружает atlas/<projId>/ из bootstrap, делает syncCheck (issues для drift/broken), persists в localStorage.",
          "sources": [
            "Sima (Remix)/atlas_sync.js [alive]"
          ],
          "tech_stack": [
            "javascript"
          ]
        }
      ],
      "links": [
        {
          "from": "b.canvas",
          "to": "b.atlas-sync",
          "type": "dep",
          "label": "arch_state",
          "capability": "arch_state",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.inspector",
          "to": "b.canvas",
          "type": "dep",
          "label": "selected_block_id",
          "capability": "selected_block_id",
          "broken": true,
          "broken_reason": "b.canvas не предоставляет capability \"selected_block_id\""
        },
        {
          "from": "b.inspector",
          "to": "b.atlas-sync",
          "type": "dep",
          "label": "arch_state",
          "capability": "arch_state",
          "broken": false,
          "broken_reason": null
        },
        {
          "from": "b.proposals-panel",
          "to": "b.atlas-sync",
          "type": "dep",
          "label": "arch_state",
          "capability": "arch_state",
          "broken": false,
          "broken_reason": null
        }
      ],
      "groups": [],
      "parent": {
        "projectId": "atlas-live",
        "blockId": "b.ui-control",
        "subId": "components"
      }
    }
  }
};

// Inject any layer ids not yet declared in ARCH_LAYERS (set by arch_data.js).
window.ARCH_LAYERS = window.ARCH_LAYERS || {};
const __atlasLayerDefs = {"user":{"id":"user","name":"Пользователь / JTBD","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"front":{"id":"front","name":"Фронтенд","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"logic":{"id":"logic","name":"Логика / бэкенд","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"ai":{"id":"ai","name":"ИИ / агенты","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"data":{"id":"data","name":"Данные / хранилище","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"ext":{"id":"ext","name":"Внешние интеграции","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"content":{"id":"content","name":"Контент / документация","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"testing":{"id":"testing","name":"Тестирование","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"}};
for (const __id in __atlasLayerDefs) {
  if (!window.ARCH_LAYERS[__id]) window.ARCH_LAYERS[__id] = __atlasLayerDefs[__id];
}

// Merge archByProject into window.ARCH_BY_PROJECT.
window.ARCH_BY_PROJECT = Object.assign(
  window.ARCH_BY_PROJECT || {},
  (window.SIMA_BOOTSTRAP && window.SIMA_BOOTSTRAP.archByProject) || {}
);

// Merge real projects into window.SIMA_DATA_V2.projects so they show in tabs.
(function mergeProjectsIntoDataV2(){
  if (!window.SIMA_DATA_V2 || !Array.isArray(window.SIMA_DATA_V2.projects)) return;
  const incoming = (window.SIMA_BOOTSTRAP.data && window.SIMA_BOOTSTRAP.data.projects) || [];
  for (const p of incoming) {
    const idx = window.SIMA_DATA_V2.projects.findIndex(x => x.id === p.id);
    if (idx >= 0) window.SIMA_DATA_V2.projects[idx] = p;
    else window.SIMA_DATA_V2.projects.unshift(p);
  }
})();
