// AUTO-GENERATED by scripts/generate_atlas_bootstrap_js.mjs — do not edit by hand
// Source: atlas/graph.json + atlas/blocks/<id>/*.md
window.SIMA_BOOTSTRAP = {
  "data": {
    "projects": [
      {
        "id": "atlas-live",
        "name": "Sima Atlas",
        "taskKind": "продукт",
        "taskTitle": "Живая схема Atlas",
        "taskNote": "Блоки, слои, статусы и зависимости автогенерируются из /atlas",
        "created": "2026-05-02",
        "owner": "Cursor / Claude / Codex",
        "canvas": {
          "task": {
            "id": "t1",
            "x": 540,
            "y": 40,
            "w": 420,
            "h": 100,
            "title": "Sima Atlas",
            "subtitle": "Многослойная схема: layer → block → файлы и связи"
          },
          "sources": [
            {
              "id": "b.ui-control",
              "type": "artifact",
              "x": 120,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "front · wip",
              "title": "UI Control Plane",
              "meta": "b.ui-control",
              "take": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
              "tags": [
                "#wip",
                "#front"
              ]
            },
            {
              "id": "b.core-sync",
              "type": "artifact",
              "x": 350,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "logic · wip",
              "title": "Sync Engine",
              "meta": "b.core-sync",
              "take": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
              "tags": [
                "#wip",
                "#logic"
              ]
            },
            {
              "id": "b.agent-orchestrator",
              "type": "artifact",
              "x": 580,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "ai · wip",
              "title": "Agent Orchestrator",
              "meta": "b.agent-orchestrator",
              "take": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
              "tags": [
                "#wip",
                "#ai"
              ]
            },
            {
              "id": "b.llm-gateway",
              "type": "artifact",
              "x": 810,
              "y": 200,
              "w": 220,
              "h": 130,
              "source": "ai · idea",
              "title": "LLM Gateway (PR3)",
              "meta": "b.llm-gateway",
              "take": "Тонкий слой к LLM-провайдерам (Claude / Gemini / OpenAI) с единым интерфейсом для всех движков Атласа: `extractBlockSchema(text) → BlockSchema`, `validateMissionMatch(mission, code",
              "tags": [
                "#idea",
                "#ai"
              ]
            },
            {
              "id": "b.db",
              "type": "artifact",
              "x": 120,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "data · idea",
              "title": "Atlas Database",
              "meta": "b.db",
              "take": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
              "tags": [
                "#idea",
                "#data"
              ]
            },
            {
              "id": "b.docs",
              "type": "artifact",
              "x": 350,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "content · wip",
              "title": "Docs Builder",
              "meta": "b.docs",
              "take": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
              "tags": [
                "#wip",
                "#content"
              ]
            },
            {
              "id": "b.smoke-sandbox",
              "type": "artifact",
              "x": 580,
              "y": 360,
              "w": 220,
              "h": 130,
              "source": "testing · idea",
              "title": "Smoke Sandbox (test target)",
              "meta": "b.smoke-sandbox",
              "take": "Целевой блок для всех e2e/smoke-тестов Атласа.",
              "tags": [
                "#idea",
                "#testing"
              ]
            }
          ],
          "links": [
            {
              "id": "b.ui-control__b.core-sync",
              "from": "b.ui-control",
              "to": "b.core-sync",
              "label": "b.ui-control → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.ui-control__b.agent-orchestrator",
              "from": "b.ui-control",
              "to": "b.agent-orchestrator",
              "label": "b.ui-control → b.agent-orchestrator",
              "direction": "to-task"
            },
            {
              "id": "b.core-sync__b.db",
              "from": "b.core-sync",
              "to": "b.db",
              "label": "b.core-sync → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.agent-orchestrator__b.db",
              "from": "b.agent-orchestrator",
              "to": "b.db",
              "label": "b.agent-orchestrator → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.agent-orchestrator__b.core-sync",
              "from": "b.agent-orchestrator",
              "to": "b.core-sync",
              "label": "b.agent-orchestrator → b.core-sync",
              "direction": "to-task"
            },
            {
              "id": "b.docs__b.db",
              "from": "b.docs",
              "to": "b.db",
              "label": "b.docs → b.db",
              "direction": "to-task"
            },
            {
              "id": "b.docs__b.core-sync",
              "from": "b.docs",
              "to": "b.core-sync",
              "label": "b.docs → b.core-sync",
              "direction": "to-task"
            }
          ]
        },
        "map": {
          "mission": {
            "id": "m.mission",
            "title": "Миссия",
            "value": "Решить рассинхрон кода между сессиями ИИ через единый source-of-truth — /atlas/",
            "filled": true
          },
          "idea": {
            "id": "m.idea",
            "title": "Идея",
            "value": "Блоки лежат как markdown-файлы; агенты читают только нужный блок, не весь чат.",
            "filled": true
          },
          "goal": {
            "id": "m.goal",
            "title": "JTBD",
            "value": "Видеть на схеме что готово, что сломано, и одной кнопкой передавать context-pack агенту.",
            "filled": true
          },
          "audience": {
            "id": "m.audience",
            "title": "Для кого",
            "value": "Solo founder + AI-coding workflows (Cursor / Claude Code / Codex / Antigravity)",
            "filled": true
          },
          "value": {
            "id": "m.value",
            "title": "Ценность",
            "value": "Меньше токенов, меньше дрейфа, единое понимание продукта между всеми агентами.",
            "filled": true
          },
          "important": {
            "id": "m.important",
            "title": "Должно быть",
            "items": [
              {
                "label": "UI Control Plane (front · wip)",
                "filled": true
              },
              {
                "label": "Sync Engine (logic · wip)",
                "filled": true
              },
              {
                "label": "Agent Orchestrator (ai · wip)",
                "filled": true
              },
              {
                "label": "LLM Gateway (PR3) (ai · idea)",
                "filled": true
              },
              {
                "label": "Atlas Database (data · idea)",
                "filled": true
              },
              {
                "label": "Docs Builder (content · wip)",
                "filled": true
              }
            ]
          },
          "userstory": {
            "id": "m.us",
            "title": "User Story (по слоям)",
            "nodes": [
              {
                "id": "b.ui-control",
                "title": "UI Control Plane",
                "kind": "блок · front",
                "filled": true,
                "body": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/Сима - универсальный конструктор.html [alive]",
                  "Sima (Remix)/app_v2.jsx [alive]",
                  "Sima (Remix)/arch_canvas.jsx [alive]",
                  "Sima (Remix)/layer1_canvas.jsx [alive]",
                  "Sima (Remix)/layer2_map.jsx [alive]"
                ]
              },
              {
                "id": "b.core-sync",
                "title": "Sync Engine",
                "kind": "блок · logic",
                "filled": true,
                "body": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
                "hasSubschema": false,
                "sources": [
                  "Sima (Remix)/atlas_sync.js [alive] (client-side syncCheck + transitions)",
                  "scripts/validate_block_contracts.mjs [alive]",
                  "scripts/validate_dependency_contracts.mjs [alive]",
                  "scripts/validate_acceptance_assertions.mjs [alive]",
                  "scripts/validate_no_template_placeholders.mjs [alive] (PR1)"
                ]
              },
              {
                "id": "b.agent-orchestrator",
                "title": "Agent Orchestrator",
                "kind": "блок · ai",
                "filled": true,
                "body": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
                "hasSubschema": false,
                "sources": [
                  "scripts/mcp_atlas_server.mjs [alive] (21+ tools over JSON-RPC stdio)",
                  "scripts/atlas_api_server.mjs [alive] (HTTP facade for orchestration)",
                  "scripts/generate_cursor_hooks.mjs [alive] (currently emits invalid hook events — fix in PR4)",
                  "scripts/generate_agent_contracts.mjs [alive] (writes AGENTS.md / CLAUDE.md)",
                  "scripts/build_context_pack.mjs [alive]"
                ]
              },
              {
                "id": "b.llm-gateway",
                "title": "LLM Gateway (PR3)",
                "kind": "блок · ai",
                "filled": true,
                "body": "Тонкий слой к LLM-провайдерам (Claude / Gemini / OpenAI) с единым интерфейсом для всех движков Атласа: `extractBlockSchema(text) → BlockSchema`, `validateMissionMatch(mission, code",
                "hasSubschema": false,
                "sources": [
                  "(none yet — PR3 will create scripts/llm_gateway.mjs and tests/llm_mocks/*)"
                ]
              },
              {
                "id": "b.db",
                "title": "Atlas Database",
                "kind": "блок · data",
                "filled": true,
                "body": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
                "hasSubschema": false,
                "sources": [
                  "atlas/graph.json [alive] (v2 — main schema source of truth)",
                  "atlas/db_schema.json [alive]",
                  "atlas/project.md [alive]",
                  "atlas/rules.md [alive]",
                  "atlas/tech_stack.md [alive] (project-wide stack lock)"
                ]
              },
              {
                "id": "b.docs",
                "title": "Docs Builder",
                "kind": "блок · content",
                "filled": true,
                "body": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
                "hasSubschema": false,
                "sources": [
                  "scripts/generate_wiki.mjs [alive]",
                  "scripts/generate_tz_from_atlas.mjs [alive]",
                  "scripts/render_wiki_html.mjs [alive]",
                  "scripts/rebuild_atlas_roadmap.mjs [alive]",
                  "scripts/generate_atlas_bootstrap_js.mjs [alive] (PR2 — emits layered bootstrap)"
                ]
              },
              {
                "id": "b.smoke-sandbox",
                "title": "Smoke Sandbox (test target)",
                "kind": "блок · testing",
                "filled": true,
                "body": "Целевой блок для всех e2e/smoke-тестов Атласа.",
                "hasSubschema": false,
                "sources": [
                  "scripts/mcp_smoke_e2e.mjs [alive] (writes only into b.smoke-sandbox)",
                  "tests/atlas_sync.selftest.mjs [alive]"
                ]
              }
            ],
            "links": [
              {
                "from": "b.ui-control",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.ui-control",
                "to": "b.agent-orchestrator",
                "label": "depends_on"
              },
              {
                "from": "b.core-sync",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.agent-orchestrator",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.agent-orchestrator",
                "to": "b.core-sync",
                "label": "depends_on"
              },
              {
                "from": "b.docs",
                "to": "b.db",
                "label": "depends_on"
              },
              {
                "from": "b.docs",
                "to": "b.core-sync",
                "label": "depends_on"
              }
            ]
          }
        },
        "tz": {
          "sections": [
            {
              "id": "s1",
              "num": "1",
              "title": "Миссия и цели"
            },
            {
              "id": "s2",
              "num": "2",
              "title": "Архитектура (по слоям)"
            },
            {
              "id": "s3",
              "num": "3",
              "title": "Блоки и контракты"
            },
            {
              "id": "s4",
              "num": "4",
              "title": "Roadmap и зависимости"
            },
            {
              "id": "s5",
              "num": "5",
              "title": "Sync-check и валидаторы"
            }
          ]
        },
        "impl": {
          "blocks": [
            {
              "id": "b.ui-control",
              "title": "UI Control Plane",
              "status": "wip",
              "layer": "front"
            },
            {
              "id": "b.core-sync",
              "title": "Sync Engine",
              "status": "wip",
              "layer": "logic"
            },
            {
              "id": "b.agent-orchestrator",
              "title": "Agent Orchestrator",
              "status": "wip",
              "layer": "ai"
            },
            {
              "id": "b.llm-gateway",
              "title": "LLM Gateway (PR3)",
              "status": "idea",
              "layer": "ai"
            },
            {
              "id": "b.db",
              "title": "Atlas Database",
              "status": "idea",
              "layer": "data"
            },
            {
              "id": "b.docs",
              "title": "Docs Builder",
              "status": "wip",
              "layer": "content"
            },
            {
              "id": "b.smoke-sandbox",
              "title": "Smoke Sandbox (test target)",
              "status": "idea",
              "layer": "testing"
            }
          ]
        }
      }
    ]
  },
  "archByProject": {
    "atlas-live": {
      "projectId": "atlas-live",
      "layers": [
        "front",
        "logic",
        "ai",
        "data",
        "content",
        "testing"
      ],
      "blocks": [
        {
          "id": "b.ui-control",
          "title": "UI Control Plane",
          "layer": "front",
          "type": "module",
          "status": "wip",
          "status_reason": "HTML loses references to components.jsx/sidecol.jsx/canvas_tools.jsx — UI does not boot in production; multi-layer rendering depends on PR2 (this PR)",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Визуальная control plane Симы: один React-канвас, в котором человек видит схему продукта (слои, блоки, связи), статус каждого блока (idea/wip/review/done/broken/drift), запускает д",
          "sources": [
            "Sima (Remix)/Сима - универсальный конструктор.html [alive]",
            "Sima (Remix)/app_v2.jsx [alive]",
            "Sima (Remix)/arch_canvas.jsx [alive]",
            "Sima (Remix)/layer1_canvas.jsx [alive]",
            "Sima (Remix)/layer2_map.jsx [alive]"
          ],
          "tech_stack": [
            "react",
            "babel-standalone"
          ]
        },
        {
          "id": "b.core-sync",
          "title": "Sync Engine",
          "layer": "logic",
          "type": "module",
          "status": "wip",
          "status_reason": "syncCheck only validates file presence, not mission/KPI semantics",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Sync Engine — движок проверки синхронизации блоков продукта с миссией, KPI, стэком и кодом.",
          "sources": [
            "Sima (Remix)/atlas_sync.js [alive] (client-side syncCheck + transitions)",
            "scripts/validate_block_contracts.mjs [alive]",
            "scripts/validate_dependency_contracts.mjs [alive]",
            "scripts/validate_acceptance_assertions.mjs [alive]",
            "scripts/validate_no_template_placeholders.mjs [alive] (PR1)"
          ],
          "tech_stack": [
            "nodejs",
            "esm"
          ]
        },
        {
          "id": "b.agent-orchestrator",
          "title": "Agent Orchestrator",
          "layer": "ai",
          "type": "module",
          "status": "wip",
          "status_reason": "No real Cursor SDK / Claude Code integration; hooks.json uses invented events",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Шина между Sima и любым coding-агентом (Cursor, Claude Code, Codex CLI, Antigravity).",
          "sources": [
            "scripts/mcp_atlas_server.mjs [alive] (21+ tools over JSON-RPC stdio)",
            "scripts/atlas_api_server.mjs [alive] (HTTP facade for orchestration)",
            "scripts/generate_cursor_hooks.mjs [alive] (currently emits invalid hook events — fix in PR4)",
            "scripts/generate_agent_contracts.mjs [alive] (writes AGENTS.md / CLAUDE.md)",
            "scripts/build_context_pack.mjs [alive]"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "mcp"
          ]
        },
        {
          "id": "b.llm-gateway",
          "title": "LLM Gateway (PR3)",
          "layer": "ai",
          "type": "module",
          "status": "idea",
          "status_reason": "Not implemented yet; PR3 will add Claude/Gemini gateway with structured output",
          "mvp": true,
          "subschema": null,
          "x": 270,
          "w": 210,
          "note": "Тонкий слой к LLM-провайдерам (Claude / Gemini / OpenAI) с единым интерфейсом для всех движков Атласа: `extractBlockSchema(text) → BlockSchema`, `validateMissionMatch(mission, code",
          "sources": [
            "(none yet — PR3 will create scripts/llm_gateway.mjs and tests/llm_mocks/*)"
          ],
          "tech_stack": [
            "nodejs",
            "anthropic-sdk",
            "google-genai"
          ]
        },
        {
          "id": "b.db",
          "title": "Atlas Database",
          "layer": "data",
          "type": "module",
          "status": "idea",
          "status_reason": "Storage is markdown + localStorage; no real DB layer yet",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Atlas storage слой: единый источник правды для графа продукта (`graph.",
          "sources": [
            "atlas/graph.json [alive] (v2 — main schema source of truth)",
            "atlas/db_schema.json [alive]",
            "atlas/project.md [alive]",
            "atlas/rules.md [alive]",
            "atlas/tech_stack.md [alive] (project-wide stack lock)"
          ],
          "tech_stack": [
            "filesystem",
            "json",
            "markdown"
          ]
        },
        {
          "id": "b.docs",
          "title": "Docs Builder",
          "layer": "content",
          "type": "module",
          "status": "wip",
          "status_reason": "Generators run but feed on template missions; needs layer-aware wiki and mermaid (PR2)",
          "mvp": true,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Документ-генератор Атласа: на каждый блок собирает живую страницу wiki из его `mission.",
          "sources": [
            "scripts/generate_wiki.mjs [alive]",
            "scripts/generate_tz_from_atlas.mjs [alive]",
            "scripts/render_wiki_html.mjs [alive]",
            "scripts/rebuild_atlas_roadmap.mjs [alive]",
            "scripts/generate_atlas_bootstrap_js.mjs [alive] (PR2 — emits layered bootstrap)"
          ],
          "tech_stack": [
            "nodejs",
            "esm",
            "markdown"
          ]
        },
        {
          "id": "b.smoke-sandbox",
          "title": "Smoke Sandbox (test target)",
          "layer": "testing",
          "type": "test",
          "status": "idea",
          "status_reason": "Reserved write-target for e2e/smoke scripts so they never touch real product blocks",
          "mvp": false,
          "subschema": null,
          "x": 40,
          "w": 210,
          "note": "Целевой блок для всех e2e/smoke-тестов Атласа.",
          "sources": [
            "scripts/mcp_smoke_e2e.mjs [alive] (writes only into b.smoke-sandbox)",
            "tests/atlas_sync.selftest.mjs [alive]"
          ],
          "tech_stack": []
        }
      ],
      "links": [
        {
          "from": "b.ui-control",
          "to": "b.core-sync",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.ui-control",
          "to": "b.agent-orchestrator",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.core-sync",
          "to": "b.db",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.agent-orchestrator",
          "to": "b.db",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.agent-orchestrator",
          "to": "b.core-sync",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.docs",
          "to": "b.db",
          "type": "dep",
          "label": ""
        },
        {
          "from": "b.docs",
          "to": "b.core-sync",
          "type": "dep",
          "label": ""
        }
      ],
      "groups": []
    }
  }
};

// Inject any layer ids that are not yet declared in ARCH_LAYERS (set by arch_data.js).
window.ARCH_LAYERS = window.ARCH_LAYERS || {};
const __atlasLayerDefs = {"user":{"id":"user","name":"Пользователь / JTBD","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"front":{"id":"front","name":"Фронтенд","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"logic":{"id":"logic","name":"Логика / бэкенд","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"ai":{"id":"ai","name":"ИИ / агенты","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"data":{"id":"data","name":"Данные / хранилище","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"ext":{"id":"ext","name":"Внешние интеграции","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"content":{"id":"content","name":"Контент / документация","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"},"testing":{"id":"testing","name":"Тестирование","hue":"#7A6A4F","bg":"rgba(122,106,79,0.06)"}};
for (const __id in __atlasLayerDefs) {
  if (!window.ARCH_LAYERS[__id]) window.ARCH_LAYERS[__id] = __atlasLayerDefs[__id];
}

// Merge archByProject into window.ARCH_BY_PROJECT (defined by arch_data.js).
window.ARCH_BY_PROJECT = Object.assign(
  window.ARCH_BY_PROJECT || {},
  (window.SIMA_BOOTSTRAP && window.SIMA_BOOTSTRAP.archByProject) || {}
);

// Merge atlas-live project into window.SIMA_DATA_V2.projects so it shows up in tabs.
(function mergeAtlasIntoDataV2(){
  if (!window.SIMA_DATA_V2 || !Array.isArray(window.SIMA_DATA_V2.projects)) return;
  const incoming = (window.SIMA_BOOTSTRAP.data && window.SIMA_BOOTSTRAP.data.projects) || [];
  for (const p of incoming) {
    const idx = window.SIMA_DATA_V2.projects.findIndex(x => x.id === p.id);
    if (idx >= 0) window.SIMA_DATA_V2.projects[idx] = p;
    else window.SIMA_DATA_V2.projects.unshift(p);
  }
})();
