// PR3.5: ProposalsPanel — Accept/Reject UI for LLM-suggested block updates.
//
// Reads pending proposals from atlas/proposals/index.json (generated by
// scripts/list_proposals.mjs --json --write-index), and lets the user:
//   * see field-by-field diff per proposal
//   * Accept  → POST /proposals/accept (atlas_api_server.mjs)
//   * Reject  → POST /proposals/reject  with optional reason
//
// In offline mode (no API server reachable) the panel falls back to displaying
// the proposals read-only with a hint: "Use CLI: node scripts/accept_proposal.mjs <id>".

const { useState, useEffect } = React;

// PR-6 (b.operator-profile-learner): compute compliance of a proposal against
// the current operator profile.
//   match    — proposed tech_stack overlaps operator's high-satisfaction
//              history; suggested_template_id is the one operator usually
//              picks for that scope.
//   conflict — proposed tech_stack contains entries listed in dont_use
//              (operator told us "never use this"); always overrides match.
//   neutral  — neither.
// Returns null when profile is in warming_up state — UI hides the badge.
function complianceWithProfile(proposal) {
  const profile = (window.SIMA_BOOTSTRAP && window.SIMA_BOOTSTRAP.operatorProfile) || null;
  const explicitDontUse = (window.SIMA_BOOTSTRAP && window.SIMA_BOOTSTRAP.operatorDontUse) || [];
  if (!profile || profile._status === 'warming_up') return null;

  const proposed = proposal.proposed || {};
  const tech = Array.isArray(proposed.tech_stack) ? proposed.tech_stack
    : (Array.isArray(proposal.changes?.tech_stack_add) ? proposal.changes.tech_stack_add : []);
  const dontUse = [...new Set([...(profile.dont_use || []), ...explicitDontUse])];
  const conflicts = tech.filter((t) => dontUse.includes(t));
  if (conflicts.length) return { kind: 'conflict', items: conflicts, reason: 'tech_stack hits dont_use' };

  const techHist = profile.tech_stack_history || {};
  const allHigh = Object.values(techHist).flat().filter((x) => x && x.uses >= 2 && x.satisfaction === 'high').map((x) => x.name);
  const overlap = tech.filter((t) => allHigh.includes(t));
  if (overlap.length) return { kind: 'match', items: overlap, reason: 'tech_stack overlaps high-satisfaction history' };

  return { kind: 'neutral', items: [], reason: 'no overlap with profile signals' };
}

function ProposalsPanel() {
  const [proposals, setProposals] = useState([]);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const [serverOk, setServerOk] = useState(true);

  async function refresh() {
    try {
      const r = await fetch('/atlas/proposals/index.json', { cache: 'no-store' });
      if (r.ok) {
        const list = await r.json();
        setProposals(Array.isArray(list) ? list.filter((p) => p.verdict === 'pending') : []);
        setError(null);
        return;
      }
      // Fallback: read individual files via known proposals listing
      // (when the index is not yet generated, we just say "0 known")
      setProposals([]);
      setError(null);
    } catch (e) {
      setError(String(e.message || e));
    }
  }

  async function callServer(endpoint, payload) {
    setBusy(true);
    try {
      const r = await fetch('http://localhost:8787' + endpoint, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await r.json().catch(() => ({}));
      if (!r.ok || !data.ok) throw new Error(data.error || ('HTTP ' + r.status));
      setServerOk(true);
      await refresh();
    } catch (e) {
      setServerOk(false);
      setError(String(e.message || e) + ' — запусти `node scripts/atlas_api_server.mjs` и обнови.');
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => { refresh(); }, []);

  if (error && !proposals.length) {
    return (
      <div className="side-sec">
        <h4 className="sec-ttl">Предложения LLM</h4>
        <div style={{ fontSize: 11, color: 'var(--ink-4)' }}>
          Нет доступного индекса предложений (atlas/proposals/index.json).
          <br/>Сгенерируй: <code>node scripts/list_proposals.mjs --json &gt; atlas/proposals/index.json</code>
        </div>
      </div>
    );
  }

  if (!proposals.length) {
    return (
      <div className="side-sec">
        <h4 className="sec-ttl">Предложения LLM</h4>
        <div style={{ fontSize: 11, color: 'var(--ink-4)' }}>
          Нет ожидающих предложений. Когда LLM-extraction предложит обновить
          существующий блок, оно появится здесь с кнопками Accept / Reject.
        </div>
      </div>
    );
  }

  return (
    <div className="side-sec">
      <h4 className="sec-ttl">Предложения LLM <span style={{ color: 'var(--orange-ink)' }}>· {proposals.length}</span></h4>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {proposals.map((p) => {
          // PR-5 (b.acceptance-verifier-loop): specialised card for
          // acceptance_regression — surfaces sample failures + a one-click
          // retry button that re-runs the configured agent on the block with
          // the verifier's retry_prompt_hint pre-pended.
          if (p.kind === 'acceptance_regression') {
            return (
              <div key={p.id} style={{
                border: '1px solid #fecaca', borderRadius: 8, padding: 10, background: '#fef2f2',
              }}>
                <div style={{ fontSize: 12, fontWeight: 600, color: '#b91c1c' }}>
                  ✗ {p.block_id}
                  <span style={{ marginLeft: 8, fontWeight: 400, fontSize: 10, color: 'var(--ink-4)' }}>
                    acceptance_regression · {p.counts?.fail || 0}/{(p.counts?.pass || 0) + (p.counts?.fail || 0) + (p.counts?.skipped || 0)} fail
                  </span>
                </div>
                <div style={{ fontSize: 10.5, color: 'var(--ink-3)', margin: '6px 0' }}>
                  was <b>done</b> → propose <b style={{color:'#b91c1c'}}>broken</b>
                </div>
                {(p.sample_failures || []).slice(0, 3).map((sf) => (
                  <div key={sf.id} style={{ fontSize: 10.5, marginTop: 4, paddingLeft: 8, borderLeft: '2px solid #fecaca' }}>
                    <b>{sf.id}</b>: <span style={{ color: 'var(--ink-3)' }}>{(sf.evidence || '').slice(0, 140)}</span>
                  </div>
                ))}
                {p.retry_prompt_hint && (
                  <div style={{ fontSize: 10, color: 'var(--ink-4)', marginTop: 6, fontStyle: 'italic' }}>
                    hint: {p.retry_prompt_hint.slice(0, 160)}{p.retry_prompt_hint.length > 160 ? '…' : ''}
                  </div>
                )}
                <div style={{ display: 'flex', gap: 6, marginTop: 8, flexWrap: 'wrap' }}>
                  <button className="btn xs" disabled={busy}
                    style={{ background: '#b91c1c', color: '#fff', borderColor: '#b91c1c' }}
                    onClick={() => callServer('/proposals/accept', { proposal_id: p.id })}>
                    Accept (→ broken)
                  </button>
                  {p.retry_prompt_hint && (
                    <button className="btn xs" disabled={busy}
                      style={{ background: '#1e40af', color: '#fff', borderColor: '#1e40af' }}
                      onClick={() => callServer('/run-block', { block_id: p.block_id, prompt: p.retry_prompt_hint })}>
                      🔁 Прогнать снова с подсказкой
                    </button>
                  )}
                  <button className="btn xs ghost" disabled={busy}
                    onClick={() => {
                      const reason = prompt('Причина отклонения (опционально):') || '';
                      callServer('/proposals/reject', { proposal_id: p.id, reason });
                    }}>
                    Reject
                  </button>
                </div>
              </div>
            );
          }
          return (
          <div key={p.id} style={{
            border: '1px solid var(--line-2)', borderRadius: 8, padding: 10, background: '#fff7ed',
          }}>
            <div style={{ fontSize: 12, fontWeight: 600 }}>
              {p.block_id}
              <span style={{ marginLeft: 8, fontWeight: 400, fontSize: 10, color: 'var(--ink-4)' }}>
                {p.source?.provider || '?'} · c={p.source?.confidence?.toFixed?.(2) ?? '?'}
              </span>
              {p.suggested_template_id && (
                <span
                  title={`Стартовый шаблон Атласа · профиль: ${p.suggested_template_profile_state || 'warming_up'}`}
                  style={{
                    marginLeft: 8, padding: '1px 6px', fontSize: 10, fontWeight: 500,
                    background: '#dbeafe', color: '#1e3a8a', borderRadius: 4, border: '1px solid #93c5fd',
                  }}>
                  template: {p.suggested_template_id}
                </span>
              )}
              {(() => {
                const c = complianceWithProfile(p);
                if (!c) return null;
                const palette = c.kind === 'match' ? { bg: '#dcfce7', tx: '#065f46', bd: '#bbf7d0', label: '✓ соответствует профилю' }
                  : c.kind === 'conflict' ? { bg: '#fef2f2', tx: '#b91c1c', bd: '#fecaca', label: '⛔ противоречит профилю' }
                  : { bg: '#f1f5f9', tx: '#475569', bd: '#e2e8f0', label: '· нейтрально' };
                return (
                  <span
                    title={`${c.reason}${c.items.length ? ' · ' + c.items.join(', ') : ''}`}
                    style={{
                      marginLeft: 8, padding: '1px 6px', fontSize: 10, fontWeight: 500,
                      background: palette.bg, color: palette.tx, borderRadius: 4, border: '1px solid ' + palette.bd,
                    }}>
                    {palette.label}
                  </span>
                );
              })()}
            </div>
            <div style={{ fontSize: 10.5, color: 'var(--ink-3)', margin: '4px 0' }}>
              {Object.entries(p.changes || {}).slice(0, 6).map(([k, v]) => (
                <div key={k}>
                  <b>{k}</b>:{' '}
                  {Array.isArray(v) ? v.join(', ') :
                    (v && typeof v === 'object' && 'from' in v) ?
                      <span><span style={{ textDecoration: 'line-through', color: 'var(--ink-4)' }}>{String(v.from)}</span> → <span style={{ color: '#16a34a' }}>{String(v.to)}</span></span>
                      : String(v).slice(0, 200)
                  }
                </div>
              ))}
            </div>
            <div style={{ display: 'flex', gap: 6, marginTop: 6 }}>
              <button className="btn xs" disabled={busy}
                style={{ background: '#16a34a', color: '#fff', borderColor: '#16a34a' }}
                onClick={() => callServer('/proposals/accept', { proposal_id: p.id })}>
                Accept
              </button>
              <button className="btn xs ghost" disabled={busy}
                onClick={() => {
                  const reason = prompt('Причина отклонения (опционально):') || '';
                  callServer('/proposals/reject', { proposal_id: p.id, reason });
                }}>
                Reject
              </button>
            </div>
          </div>
          );
        })}
      </div>
      {!serverOk && (
        <div style={{ marginTop: 8, padding: 8, background: '#fef2f2', borderRadius: 6, fontSize: 10.5, color: '#7f1d1d' }}>
          Сервер atlas_api недоступен. Запусти его в терминале:
          <br/><code>node scripts/atlas_api_server.mjs</code>
        </div>
      )}
      <div style={{ marginTop: 8, fontSize: 10, color: 'var(--ink-4)' }}>
        Accept применяет структурные изменения (layer / status / depends_on / tech_stack) — миссия / KPI остаются человеческими.
      </div>
    </div>
  );
}

window.ProposalsPanel = ProposalsPanel;
