#!/usr/bin/env node
// PR-2 (b.user-docs-generator): LLM-driven end-user tutorial writer.
//
// Combines PR-1 introspectBlock output with the block's mission.md and
// asks b.llm-gateway to produce an end-user tutorial — JSON Schema-driven
// so the output is structurally guaranteed regardless of provider.
//
// Pipeline:
//   1. Read mission.md (UI-facing one-liner) + introspect alive JSX/HTML
//   2. Build a prompt that EXPLICITLY forbids technical jargon
//   3. callLLM with UserTutorial schema; capped at $0.03/run
//   4. Render JSON → markdown (`<!-- AUTOGENERATED -->` header + frontmatter)
//   5. Compute hash of {mission_md, introspect_json}; skip write if hash
//      matches existing _meta entry (idempotent regen)
//   6. Atomic-replace markdown + meta files
//
// API:
//   import { generateUserDocs } from './generate_user_docs.mjs';
//   const r = await generateUserDocs({ block_id, lang, dry_run });
//   r → { block_id, file, status: 'written'|'unchanged'|'locked'|'no_ui',
//         cost_usd, provider, model, hash, warnings }
//
// CLI:
//   node scripts/generate_user_docs.mjs <block_id>          # generate
//   node scripts/generate_user_docs.mjs <block_id> --dry-run
//   node scripts/generate_user_docs.mjs <block_id> --lang en
//   node scripts/generate_user_docs.mjs <block_id> --json   # also dump result
//
// Env:
//   LLM_MAX_USD_PER_RUN — default 0.03
//   ATLAS_USER_DOCS_LANG — default ru (override per-call via --lang)

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { callLLM } from './llm_gateway.mjs';
import { introspectBlock } from './introspect_block_ui.mjs';

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), '..');
const ATLAS = process.env.ATLAS_ROOT || path.join(ROOT, 'atlas');
const COST_CAP_USD = Number(process.env.LLM_MAX_USD_PER_RUN || 0.03);
const DEFAULT_LANG = process.env.ATLAS_USER_DOCS_LANG || 'ru';

// Words that should NOT appear in the user-facing tutorial body (only in the
// "Под капотом" section). Detected post-LLM; on violation we either retry
// once with a stricter prompt or fall back to a tagged warning.
const JARGON_TOKENS = ['module', 'modules', 'component', 'components', 'endpoint',
  'endpoints', 'prop', 'props', 'state', 'states', 'function', 'functions',
  'import', 'imports', 'mount', 'unmount'];

export const USER_TUTORIAL_SCHEMA = {
  type: 'object',
  required: ['title', 'oneliner', 'steps'],
  properties: {
    title: { type: 'string' },
    oneliner: { type: 'string' },
    steps: {
      type: 'array',
      items: {
        type: 'object',
        required: ['action', 'target'],
        properties: {
          action: { type: 'string' },     // "Нажми", "Открой", "Заполни"
          target: { type: 'string' },     // "+ Новая задача", "/tasks", "Название"
          expected: { type: 'string' },   // "откроется форма" / ""
        },
      },
    },
    troubleshooting: {
      type: 'array',
      items: {
        type: 'object',
        required: ['problem', 'fix'],
        properties: {
          problem: { type: 'string' },
          fix: { type: 'string' },
        },
      },
    },
    under_the_hood: {
      type: 'object',
      properties: {
        block_id: { type: 'string' },
        related_apis: { type: 'array', items: { type: 'string' } },
      },
    },
  },
};

function readMission(blockId) {
  const p = path.join(ATLAS, 'blocks', blockId, 'mission.md');
  return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
}

function compactIntrospection(intro) {
  // Trim noisy fields (file/line, raw on_click bodies) — the LLM only needs
  // the user-visible labels and their grouping. Saves tokens.
  return {
    buttons: (intro.buttons || []).map((b) => b.label).filter(Boolean).slice(0, 60),
    inputs: (intro.inputs || []).map((i) => ({
      type: i.type, name: i.name, placeholder: i.placeholder, required: !!i.required,
    })).slice(0, 40),
    textareas: (intro.textareas || []).map((t) => ({ name: t.name, placeholder: t.placeholder })).slice(0, 10),
    forms: (intro.forms || []).map((f) => ({ action: f.action, method: f.method })).slice(0, 10),
    routes: (intro.routes || []).map((r) => r.path).slice(0, 30),
    links: (intro.links || []).map((l) => ({ kind: l.kind, target: l.target, label: l.label })).slice(0, 30),
    fetches: (intro.fetches || []).map((f) => ({ method: f.method, url: f.url })).slice(0, 20),
  };
}

function buildPrompt({ blockId, mission, introspection, lang }) {
  const langLabel = lang === 'en' ? 'English' : 'русском';
  const jargonList = JARGON_TOKENS.join(', ');
  return [
    `You are writing an end-user tutorial — a person clicking around the UI, NOT a developer reading code. Output language: ${langLabel}.`,
    '',
    `# Block: ${blockId}`,
    '',
    '## Mission (1-2 sentences for context)',
    String(mission || '').slice(0, 600),
    '',
    '## UI elements introspected from JSX',
    JSON.stringify(introspection, null, 2).slice(0, 4000),
    '',
    '## Output',
    'Return JSON matching the UserTutorial schema:',
    '  - title: short user-friendly feature name (5-8 words max)',
    '  - oneliner: one sentence of WHAT this lets the user do',
    '  - steps: 3-7 ordered actions, each {action, target, expected}',
    '       action — verb in user language: "Нажми", "Открой", "Заполни"',
    '       target — exact button label or input placeholder verbatim from UI',
    '       expected — what the user will see/feel afterwards (1 short phrase)',
    '  - troubleshooting: 1-3 common-mistake → fix pairs, optional',
    '  - under_the_hood: { block_id, related_apis: [list of fetch URLs] }',
    '',
    '## Hard rules',
    `- DO NOT use these technical words in title / oneliner / steps: ${jargonList}`,
    '- "under_the_hood" can use technical terms — that section is for curious users',
    '- Cite real UI labels: do not invent buttons that aren\'t in the introspection',
    '- If introspection has zero buttons/inputs/routes — return a minimal stub',
    '  (title="Возможности модуля X", steps with mission paraphrase) and add',
    '  a single troubleshooting entry "UI ещё не реализован" → "обратитесь к разработчику"',
  ].join('\n');
}

function hashSources({ mission, introspection }) {
  const h = crypto.createHash('sha256');
  h.update(String(mission || ''));
  h.update('\0');
  h.update(JSON.stringify(introspection));
  return h.digest('hex').slice(0, 16);
}

function renderMarkdown({ tutorial, blockId, hash, sourceFiles, lang, generated_at }) {
  const head = [
    '<!-- AUTOGENERATED by scripts/generate_user_docs.mjs — do not edit by hand -->',
    `<!-- block: ${blockId} -->`,
    `<!-- hash: ${hash} -->`,
    `<!-- generated_at: ${generated_at} -->`,
    `<!-- lang: ${lang} -->`,
    '',
    `# ${tutorial.title}`,
    '',
    '> Эта страница автогенерирована Атласом. Не редактируй вручную — изменения перезапишутся.',
    '',
  ];
  const oneliner = [tutorial.oneliner ? `_${tutorial.oneliner}_` : '', ''];
  const stepsHeader = (lang === 'en' ? '## Steps' : '## Шаги');
  const steps = [stepsHeader, ''];
  (tutorial.steps || []).forEach((s, i) => {
    const expected = s.expected ? ` — ${s.expected}` : '';
    steps.push(`${i + 1}. **${s.action}** ${s.target}${expected}.`);
  });
  steps.push('');
  const tsBlock = [];
  if (Array.isArray(tutorial.troubleshooting) && tutorial.troubleshooting.length) {
    tsBlock.push(lang === 'en' ? '## If something goes wrong' : '## Если что-то не получилось', '');
    for (const t of tutorial.troubleshooting) tsBlock.push(`- **${t.problem}** → ${t.fix}.`);
    tsBlock.push('');
  }
  const uthBlock = [];
  if (tutorial.under_the_hood) {
    uthBlock.push(lang === 'en' ? '## Under the hood' : '## Под капотом', '');
    if (tutorial.under_the_hood.block_id) uthBlock.push(`- Module: \`${tutorial.under_the_hood.block_id}\``);
    if (Array.isArray(tutorial.under_the_hood.related_apis) && tutorial.under_the_hood.related_apis.length) {
      uthBlock.push(`- Related APIs: ${tutorial.under_the_hood.related_apis.map((u) => `\`${u}\``).join(', ')}`);
    }
    uthBlock.push('');
  }
  const trailer = [
    '---',
    `_Sources: ${sourceFiles.map((f) => `\`${f}\``).join(', ') || '(none)'} · hash \`${hash}\`_`,
    '',
  ];
  return [...head, ...oneliner, ...steps, ...tsBlock, ...uthBlock, ...trailer].join('\n');
}

function detectJargon(tutorial) {
  const text = JSON.stringify({
    title: tutorial.title,
    oneliner: tutorial.oneliner,
    steps: tutorial.steps,
    troubleshooting: tutorial.troubleshooting,
  }).toLowerCase();
  const hits = JARGON_TOKENS.filter((w) => new RegExp(`\\b${w}\\b`, 'i').test(text));
  return hits;
}

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }

function readMeta(metaPath) {
  if (!fs.existsSync(metaPath)) return null;
  try { return JSON.parse(fs.readFileSync(metaPath, 'utf8')); } catch { return null; }
}

export async function generateUserDocs({ block_id, lang = DEFAULT_LANG, dry_run = false } = {}) {
  if (!block_id) throw new Error('generateUserDocs: block_id required');

  const mission = readMission(block_id);
  const introspection = compactIntrospection(introspectBlock(block_id, { atlas_root: ATLAS }));
  const sourceFiles = introspectBlock(block_id, { atlas_root: ATLAS }).files_scanned;
  const hash = hashSources({ mission, introspection });

  // Output paths — top-level docs/ for atlas-live, projects/<p>/docs/ for
  // project-scoped blocks. We default to atlas/docs/end-user/ unless we
  // can find the block under projects/<proj>/.
  const docsRoot = path.join(ATLAS, 'docs', 'end-user');
  const metaDir = path.join(docsRoot, '_meta');
  const docPath = path.join(docsRoot, `${block_id}.md`);
  const metaPath = path.join(metaDir, `${block_id}.json`);

  // Locked flag — operator can pin a tutorial to manual editing
  const existingMeta = readMeta(metaPath);
  if (existingMeta && existingMeta.locked === true) {
    return {
      block_id, file: docPath, status: 'locked', hash,
      warnings: ['LOCKED: true in meta — manual edit preserved'],
    };
  }

  // Idempotency: skip write when hash matches and file exists
  if (existingMeta && existingMeta.hash === hash && fs.existsSync(docPath) && !dry_run) {
    return {
      block_id, file: docPath, status: 'unchanged', hash,
      cost_usd: 0, provider: 'cache',
    };
  }

  const t0 = Date.now();
  const prompt = buildPrompt({ blockId: block_id, mission, introspection, lang });
  const result = await callLLM({
    prompt,
    schema: USER_TUTORIAL_SCHEMA,
    op: 'generate_user_docs',
    max_tokens: 1024,
    temperature: 0,
  });
  const trace = result.trace || {};
  const cost = Number(trace.cost_usd || 0);
  if (cost > COST_CAP_USD) {
    return {
      block_id, file: docPath, status: 'cost_capped', hash,
      cost_usd: cost, provider: trace.provider, model: trace.model,
      warnings: [`cost cap exceeded: $${cost.toFixed(4)} > $${COST_CAP_USD}`],
    };
  }

  let tutorial = result.value || {};
  // Defensive defaults so renderer doesn't crash on schema-empty responses
  if (!tutorial.title) tutorial.title = (lang === 'en' ? `${block_id} — overview` : `${block_id} — обзор`);
  if (!tutorial.oneliner) tutorial.oneliner = (mission || '').split(/\r?\n/).find((l) => l.trim()) || '';
  if (!Array.isArray(tutorial.steps)) tutorial.steps = [];
  if (!tutorial.under_the_hood) tutorial.under_the_hood = { block_id, related_apis: introspection.fetches.map((f) => f.url) };

  const warnings = [];
  const jargon = detectJargon(tutorial);
  if (jargon.length) warnings.push(`jargon detected: ${jargon.join(', ')}`);

  const generated_at = new Date().toISOString();
  const md = renderMarkdown({ tutorial, blockId: block_id, hash, sourceFiles, lang, generated_at });

  if (dry_run) {
    return {
      block_id, file: docPath, status: 'dry_run', hash,
      cost_usd: cost, provider: trace.provider, model: trace.model,
      duration_ms: Date.now() - t0, markdown: md, warnings,
    };
  }

  ensureDir(docsRoot); ensureDir(metaDir);
  fs.writeFileSync(docPath, md, 'utf8');
  fs.writeFileSync(metaPath, JSON.stringify({
    block_id,
    hash,
    generated_at,
    lang,
    cost_usd: cost,
    provider: trace.provider,
    model: trace.model,
    source_files: sourceFiles,
    locked: false,
    warnings,
  }, null, 2) + '\n', 'utf8');

  return {
    block_id, file: docPath, status: 'written', hash,
    cost_usd: cost, provider: trace.provider, model: trace.model,
    duration_ms: Date.now() - t0, warnings,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  const blockId = argv.find((a) => !a.startsWith('--'));
  const json = argv.includes('--json');
  const dry = argv.includes('--dry-run');
  const langIdx = argv.indexOf('--lang');
  const lang = langIdx >= 0 ? argv[langIdx + 1] : DEFAULT_LANG;
  if (!blockId) {
    console.error('Usage: node scripts/generate_user_docs.mjs <block_id> [--lang ru|en] [--dry-run] [--json]');
    process.exit(1);
  }
  const r = await generateUserDocs({ block_id: blockId, lang, dry_run: dry });
  if (json) console.log(JSON.stringify(r, null, 2));
  else {
    console.log(`generate_user_docs: ${blockId} → ${r.status} (hash=${r.hash}, ${r.provider || '?'}, $${(r.cost_usd || 0).toFixed(5)})`);
    if (r.file) console.log(`  file: ${path.relative(ROOT, r.file)}`);
    if (r.warnings && r.warnings.length) for (const w of r.warnings) console.log(`  ⚠ ${w}`);
  }
}
